import StoreStatus from '@/components/store-status';
import RegularFavorite from '@/components/regular-favorite';
import Link from 'next/link';
import BookingActions from '@/components/booking-actions';
import FlavorHeader from '@/components/flavor-header';
import ReviewLink from '@/components/review-link';
import {menuByPlaceId} from '@/lib/menu-catalog';import {money} from '@/lib/menus';import {siteConfig,variantForHost} from '@/lib/site-config';import {headers} from 'next/headers';import {notFound} from 'next/navigation';import {config} from '@/lib/server';
export default async function Page({params}:{params:Promise<{id:string}>}){const variant=variantForHost((await headers()).get('host')),theme=siteConfig(variant),{id}=await params,m=await menuByPlaceId(id,variant);if(!m)notFound();const {chatUrl}=config();return <><FlavorHeader/><main className={`place-page ${!m.isDemo&&!m.ownerRegistered?'place-page--reported':''}`}><div className="eyebrow">{theme.name}에서 발견한 한 접시 · 매장 확인</div><h1>{m.shop}</h1><p className="place-warning">{m.isDemo?'실제로 영업하지 않는 개발용 가매장입니다. 현실에 없는 매장입니다.':m.ownerRegistered?'점주 가입매장입니다. 최신 영업현황은 아래에서 확인하세요.':'제보자 등록매장 · 영업현황 확인불가 · 점주 가입 시, 실시간 영업현황 보기 가능'}</p><img className="place-photo" src={m.image} alt={`${m.name} 참고 사진`}/><div className="place-columns"><section><h2>{m.name}</h2><p>{money(m.price)} · {m.isDemo?'예시 가격':m.verifiedOwner?'점주 제보 가격':'고객 제보 가격'} · {theme.heat[m.heat-1]}</p><StoreStatus key={m.id} menuId={m.id} isDemo={m.isDemo} ownerRegistered={m.ownerRegistered}/><RegularFavorite key={m.placeId} placeId={m.placeId} slug={m.nowgoSlug} isDemo={m.isDemo}/><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8,marginTop:16}} aria-label="매장 예약·웨이팅"><BookingActions placeId={m.placeId} isDemo={m.isDemo} variant={variant} storeName={m.shop}/></div></section><section><h2>확인하고 출발해요.</h2><p>실제 운영 매장과 현재 영업·품절 정보는 NOWGO에서 확인하세요.</p><a className="submit-button" href={m.nowgoSlug?`/go/${m.placeId}`:"https://www.nowgo.space/"}>NOWGO 매장으로 이동 ↗</a>{chatUrl?<a className="text-link" href={chatUrl} target="_blank" rel="noreferrer">카카오톡으로 문의 ↗</a>:null}<ReviewLink placeId={m.placeId} isDemo={m.isDemo}/><a className="text-link" href="https://www.nowgo.space/owner/login" target="_blank" rel="noreferrer">NOWGO 점주 가입하기 ↗</a><a className="text-link" href="/suggestion#report">메뉴 정보 정정하기 ↗</a></section></div><section className="place-alternatives"><h2>다른 한 접시도 살펴볼까요?</h2>{theme.menus.filter(x=>x.id!==m.id).map(x=><a key={x.id} href={`/suggestion?menu=${x.id}`}><span>{x.name}</span><span>{money(x.price)} · 예시 →</span></a>)}</section><Link className="text-link" href="/">← {theme.name} 메뉴 지도로 돌아가기</Link></main></>}

