import type {SiteVariant} from './site-config';
export const OWNER_STATES=[['open','정상운영'],['temporary_closed','임시휴무'],['closed_for_day','영업마감'],['ingredients_soldout','재료소진'],['permanently_closed','폐업'],['break_time','브레이크 타임']] as const;
export type Appointment={id:string;kind:'reservation'|'waiting';status:string;guest_name:string|null;party_size:number;scheduled_at:string|null;queue_position:number|null;service_date:string};
export type OwnerMenu={id:string;name:string;price:number;level:number;flavor:string;category:string;photoPath:string;soldout:boolean};
export type OwnerState={checkedAt:string;status:{value:string;set_at:string;expires_at:string|null}|null;featured:{name:string;priceText:string|null;planet:SiteVariant;level:number;imageUrl:string}|null;settings:{reservations_enabled:boolean;waiting_until:string|null;max_party_size:number;max_waiting_teams:number}|null;slots:{id:string;starts_at:string;capacity:number;enabled:boolean}[];appointments:Appointment[];availability:{waitingCount:number;waitingBlocked:boolean;slots:{id:string;startsAt:string;remaining:number}[]}};
export type OwnerSnapshot={stores:{id:string;name:string;penaltyPoints?:number}[];storeId:string|null;access:{enabled:boolean;code?:string;message?:string};state:{checkedAt:string;status:{value:string;set_at:string;expires_at:string|null}|null;menus:OwnerMenu[]}|null};
export function localKoreanInput(iso:string){return new Date(Date.parse(iso)+9*3600000).toISOString().slice(0,16)}
export function fromKoreanInput(value:string){const date=new Date(`${value}:00+09:00`);if(!Number.isFinite(date.getTime()))throw new Error('날짜와 시간을 확인해 주세요.');return date.toISOString()}
export function confirmedToday(setAt:string|undefined,now:string){if(!setAt||!Number.isFinite(Date.parse(setAt))||Date.parse(setAt)>Date.parse(now))return false;return new Date(Date.parse(setAt)+5*3600000).toISOString().slice(0,10)===new Date(Date.parse(now)+5*3600000).toISOString().slice(0,10)}
export function currentWaiting(items:Appointment[],now:string){const day=new Date(Date.parse(now)+9*3600000).toISOString().slice(0,10);return items.filter(item=>item.kind==='waiting'&&item.service_date===day&&['waiting','called'].includes(item.status))}
