import {env} from 'cloudflare:workers';
import {db,session} from './server';
import {nowgoUrl,returnPath} from './integration-policy';
const settings=()=>env as unknown as Record<string,string>;
const digest=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const random=()=>crypto.randomUUID()+crypto.randomUUID();
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=(value:string)=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export function unifiedConfig(){const e=settings(),authorize=nowgoUrl(e.NOWGO_AUTH_AUTHORIZE_URL),token=nowgoUrl(e.NOWGO_AUTH_TOKEN_URL),userinfo=nowgoUrl(e.NOWGO_AUTH_USERINFO_URL),account=nowgoUrl(e.NOWGO_ACCOUNT_URL);return {authorize,token,userinfo,account,clientId:e.NOWGO_AUTH_CLIENT_ID||'',secret:e.NOWGO_AUTH_CLIENT_SECRET||'',redirect:e.NOWGO_AUTH_REDIRECT_URI||'',seal:e.NOWGO_SESSION_ENCRYPTION_KEY||'',ready:!!(authorize&&token&&userinfo&&e.NOWGO_AUTH_CLIENT_ID&&e.NOWGO_AUTH_CLIENT_SECRET&&e.NOWGO_AUTH_REDIRECT_URI&&e.NOWGO_SESSION_ENCRYPTION_KEY?.length>=32)}}
export function browserAuthConfig(){const c=unifiedConfig();return {mode:'unified',ready:c.ready,accountUrl:c.account?.toString()||null}}
function cookie(req:Request,name:string,value:string,age:number){return `${name}=${value}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`}
function readCookie(req:Request,name:string){return req.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1)||''}
async function key(){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(unifiedConfig().seal)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));return b64(iv)+'.'+b64(new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),new TextEncoder().encode(value))))}
async function unseal(value:string){const [iv,cipher]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await key(),unb64(cipher)))}
export type UnifiedMember={id:string;nickname:string;phoneMasked:string;phoneVerified:boolean;canonicalId:string;points:number|null};
async function profile(access:string):Promise<UnifiedMember|null>{const c=unifiedConfig();if(!c.ready)return null;const r=await fetch(c.userinfo!,{headers:{Authorization:'Bearer '+access},redirect:'error',signal:AbortSignal.timeout(6000)});if(!r.ok)return null;const p=await r.json() as Record<string,unknown>;if(typeof p.sub!=='string'||!/^[-a-zA-Z0-9_]{1,128}$/.test(p.sub)||p.status!=='active'||typeof p.nickname!=='string'||p.nickname.length>40||!p.nickname.trim())return null;return {id:'nowgo:'+p.sub,canonicalId:p.sub,nickname:p.nickname,phoneMasked:typeof p.phone_masked==='string'&&/^[+\d *-]{6,25}$/.test(p.phone_masked)&&p.phone_masked.includes('*')?p.phone_masked:'비공개',phoneVerified:p.phone_verified===true,points:Number.isSafeInteger(p.verified_contribution_points)&&Number(p.verified_contribution_points)>=0?Number(p.verified_contribution_points):null}}
export async function unifiedMember(req:Request):Promise<UnifiedMember|null>{if(!unifiedConfig().ready)return null;const token=readCookie(req,'nowgo_hot_auth');if(!/^[a-f0-9-]{72}$/.test(token))return null;const row=await db().prepare('SELECT subject,access_token FROM unified_sessions WHERE token_hash=? AND expires_at>?').bind(await digest(token),new Date().toISOString()).first<{subject:string,access_token:string}>();if(!row)return null;try{const member=await profile(await unseal(row.access_token));return member?.canonicalId===row.subject?member:null}catch{return null}}
export async function beginLogin(req:Request){const c=unifiedConfig();if(!c.ready)return Response.redirect(new URL('/account?connection=pending',req.url),303);if(c.redirect!==new URL('/api/auth/callback',req.url).toString())return new Response('로그인 주소 연결을 확인하고 있어요.',{status:503});const state=random(),verifier=random(),challenge=b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));const path=returnPath(new URL(req.url).searchParams.get('returnTo'));await db().prepare('DELETE FROM unified_auth_requests WHERE expires_at<?').bind(new Date().toISOString()).run();await db().prepare('INSERT INTO unified_auth_requests(state_hash,verifier,return_to,expires_at) VALUES(?,?,?,?)').bind(await digest(state),verifier,path,new Date(Date.now()+600000).toISOString()).run();const u=new URL(c.authorize!);for(const [k,v] of Object.entries({response_type:'code',client_id:c.clientId,redirect_uri:c.redirect,state,code_challenge:challenge,code_challenge_method:'S256',scope:'profile hot:contribute'}))u.searchParams.set(k,v);return new Response(null,{status:303,headers:{Location:u.toString(),'Cache-Control':'no-store','Set-Cookie':cookie(req,'nowgo_hot_state',state,600)}})}
export async function finishLogin(req:Request){const c=unifiedConfig(),u=new URL(req.url),state=u.searchParams.get('state')||'',code=u.searchParams.get('code')||'';const fail=()=>new Response(null,{status:303,headers:{Location:'/account?connection=failed','Cache-Control':'no-store','Set-Cookie':cookie(req,'nowgo_hot_state','',0)}});if(!c.ready||c.redirect!==new URL('/api/auth/callback',req.url).toString()||!code||code.length>2048||!state||state!==readCookie(req,'nowgo_hot_state'))return fail();const row=await db().prepare('DELETE FROM unified_auth_requests WHERE state_hash=? AND expires_at>? RETURNING verifier,return_to').bind(await digest(state),new Date().toISOString()).first<{verifier:string,return_to:string}>();if(!row)return fail();try{const r=await fetch(c.token!,{method:'POST',redirect:'error',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code,client_id:c.clientId,client_secret:c.secret,redirect_uri:c.redirect,code_verifier:row.verifier}),signal:AbortSignal.timeout(8000)});if(!r.ok)return fail();const p=await r.json() as {access_token?:string;token_type?:string;expires_in?:number};if(!p.access_token||p.access_token.length>16000||p.token_type?.toLowerCase()!=='bearer'||!Number.isFinite(p.expires_in)||Number(p.expires_in)<=0)return fail();const member=await profile(p.access_token);if(!member)return fail();const token=random(),age=Math.min(Number(p.expires_in),3600),anon=session(req);const writes=[db().prepare('INSERT INTO unified_sessions(token_hash,subject,access_token,expires_at) VALUES(?,?,?,?)').bind(await digest(token),member.canonicalId,await seal(p.access_token),new Date(Date.now()+age*1000).toISOString())];if(!anon.fresh){writes.push(db().prepare('UPDATE OR IGNORE menu_saves SET session=? WHERE session=?').bind(member.id,anon.id),db().prepare('DELETE FROM menu_saves WHERE session=?').bind(anon.id))}await db().batch(writes);const h=new Headers({Location:returnPath(row.return_to),'Cache-Control':'no-store'});h.append('Set-Cookie',cookie(req,'nowgo_hot_auth',token,age));h.append('Set-Cookie',cookie(req,'nowgo_hot_state','',0));h.append('Set-Cookie',cookie(req,'hot_auth','',0));return new Response(null,{status:303,headers:h})}catch{return fail()}}
export async function logoutUnified(req:Request){const token=readCookie(req,'nowgo_hot_auth');if(token)await db().prepare('DELETE FROM unified_sessions WHERE token_hash=?').bind(await digest(token)).run();const h=new Headers({'Cache-Control':'no-store','Content-Type':'application/json'});h.append('Set-Cookie',cookie(req,'nowgo_hot_auth','',0));h.append('Set-Cookie',cookie(req,'hot_auth','',0));return new Response(JSON.stringify({ok:true}),{headers:h})}
