'use client';
import {useEffect,useState,type CSSProperties,type FormEvent} from 'react';
import {Bell,Check,Compass,Camera,MapPin,Share2,Download,RefreshCw,LogOut,ChevronRight,Flag,Shield,Flame,BookOpen,Sparkles} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api} from '@/lib/client';
import {browserDb} from '@/lib/supabase-browser';
import {activityAction,captureVisit} from '@/lib/activity/client';
import {WORLDS,RANKS,BADGES,growth,type Planet,type ActivitySnapshot,type Visit} from '@/lib/activity/model';
import {useActivity} from './use-activity';
import CharacterArt from './character-art';
import ShareCard from './share-card';
import StorePicker,{type StoreChoice} from '@/components/store-picker';
const LABELS:Record<string,string>={recorded:'기록됨',published:'제보 공개',verified:'인증 완료',completed:'완료',pending:'확인 중',accepted:'채택',confirmed:'예약 확정',waiting:'대기 중',called:'입장 호출',seated:'입장 완료',cancelled:'취소',rejected:'반려',revoked:'철회'};
const date=(x:string)=>new Date(x).toLocaleDateString('ko-KR',{month:'long',day:'numeric',timeZone:'Asia/Seoul'});
const countryName=(x:string)=>{try{return new Intl.DisplayNames(['ko'],{type:'region'}).of(x)||x}catch{return x}};
const asset=(x:string)=>'/activity/'+x;
export type ActivityState=ReturnType<typeof useActivity>;
function Title({title,children}:{title:string;children:React.ReactNode}){return <div className="aw-title"><h2>{title}</h2><p>{children}</p></div>}
function Empty({children}:{children:React.ReactNode}){return <div className="aw-empty"><Compass size={27}/><p>{children}</p></div>}
function VisitList({visits,onShare}:{visits:Visit[];onShare:(v:Visit)=>void}){return <div className="aw-visits">{visits.map(v=><article className="aw-visit" key={v.id}><div className="aw-visit-icon"><Flag size={22}/></div><div><strong>{v.shop}</strong><p>{v.menu||'나의 한 접시'} · {v.region||v.country}</p><small>{v.visited_on} · {v.status==='verified'?'GPS·결제 인증':'나의 기록 · 인증 대기'}</small>{v.note&&<p>{v.note}</p>}{v.taste&&<small>맛 만족 {v.taste}/5 · 식감 만족 {v.texture||'미기록'}/5</small>}<button onClick={()=>onShare(v)} style={{display:'flex',marginTop:8,color:'var(--planet)'}}>방문 기록 공유</button></div><span className={'aw-pill '+(v.status==='verified'?'is-earned':'')}>{v.status==='verified'?'정복':'기록'}</span></article>)}</div>}

export default function ActivityWorld({planet,state,initialTab='info'}:{planet:Planet;state:ActivityState;initialTab?:string}){
 const {data:d,error,signedIn,connected,refresh}=state,w=WORLDS[planet];const [tab,setTab]=useState(initialTab),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState(false),[form,setForm]=useState<'visit'|'receipt'|'status'|null>(null),[store,setStore]=useState<StoreChoice|null>(null),[nickname,setNickname]=useState(''),[character,setCharacter]=useState(0),[characterName,setCharacterName]=useState(''),[scale,setScale]=useState<'region'|'country'|'world'>('region'),[country,setCountry]=useState('KR'),[region,setRegion]=useState(''),[shareUrl,setShareUrl]=useState(''),[cardOpen,setCardOpen]=useState(false);
 useEffect(()=>{const value=new URLSearchParams(location.search).get('tab');if(value&&['info','awards','territory','visits','photos','history'].includes(value))setTab(value)},[]);
 const g=growth(d?.xp||0),visits=d?.visits.filter(v=>v.status==='verified')||[],groups=new Map<string,Visit[]>();for(const v of visits){const key=scale==='world'?v.country:scale==='country'?v.region:v.shop;if(scale!=='world'&&v.country!==country)continue;if(scale==='region'&&region&&v.region!==region)continue;groups.set(key,[...(groups.get(key)||[]),v])}
 async function run(fn:()=>Promise<unknown>,success:string){if(busy)return;setBusy(true);setMessage('');try{await fn();await refresh();setMessage(success)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function push(){const {key}=await api<{key:string}>('/api/activity/push-key');if(!key)throw new Error('푸시 알림을 준비하고 있어요. 새 훈장은 알림함에 보관됩니다.');if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('이 기기에서는 알림함으로 소식을 확인해 주세요.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('기기 설정에서 알림을 허용하면 다정한 소식을 전해드릴게요.');const reg=await navigator.serviceWorker.register('/activity-sw.js');await navigator.serviceWorker.ready;const padded=key.replace(/-/g,'+').replace(/_/g,'/');const bytes=Uint8Array.from(atob(padded),c=>c.charCodeAt(0));const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});const j=sub.toJSON();await activityAction('push',{endpoint:j.endpoint,p256dh:j.keys?.p256dh,auth:j.keys?.auth});}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!store){setMessage('먼저 매장을 선택해 주세요.');return}const f=new FormData(e.currentTarget);f.set('storeId',store.id);await run(async()=>{if(form==='receipt'){f.set('paidAt',new Date(String(f.get('paidAt'))).toISOString());await api('/api/activity/receipt',{method:'POST',body:f})}else if(form==='status'){await activityAction('status',{storeId:store.id,state:f.get('state'),note:f.get('note')})}else{await activityAction('visit',{storeId:store.id,date:f.get('date'),menu:f.get('menu'),note:f.get('note'),taste:Number(f.get('taste')),texture:Number(f.get('texture'))})}setForm(null)},form==='receipt'?'영수증을 보관했어요. 매장 확인과 GPS 기록이 만나면 방문이 인증돼요.':form==='status'?'소중한 제보를 보냈어요. 매장에서 확인하면 EXP에 반영돼요.':'나의 방문 기록을 보관했어요.');}
 return <div className="activity-world" style={{'--planet':w.accent} as CSSProperties}>
 <header className="aw-world-heading"><div><span className="aw-eyebrow">NOWGO · {w.name}</span><h1>나의 모험 기록</h1><p>{w.motto} 한 접시씩, 나의 왕국을 만들어 가요.</p></div><img src={asset(`planet-${planet}.webp`)} alt={`${w.name} 행성`} /></header>
 <section className="aw-world-story"><h2>취향이 신뢰가 돼요</h2><p>{w.challenge} 맛과 식감은 따로 기록해요. 내가 확인한 영업·품절 정보와 인증한 한 접시가 다음 탐험가의 확신이 됩니다.</p></section>
 {signedIn===null&&<p role="status" className="aw-loading">나의 기록을 불러오고 있어요.</p>}
 {signedIn===false&&<section className="aw-panel aw-signin"><CharacterArt planet={planet} index={0} label="대표 메뉴를 든 탐험가"/><div><Title title="첫 모험을 시작해요">{w.story}</Title><p>레벨 1, EXP 0. 캐릭터·훈장·내 영토를 같은 계정에 차곡차곡 기록해요.</p><a className="aw-button" href={'/account/join?returnTo='+encodeURIComponent('/activity')}>통합 로그인·회원가입</a></div></section>}
 {error&&<div className="aw-error" role="alert">{error}<button onClick={()=>void refresh()}>다시 불러오기</button></div>}
 {d&&<><div className="aw-top-actions"><span>{connected?'실시간 연결':'자동 갱신'} · {d.updated_at?new Date(d.updated_at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):''}</span><div><button onClick={()=>void run(push,'새 훈장이 찾아오면 알려드릴게요.')} disabled={busy}><Bell size={16}/>푸시 받기</button><button onClick={()=>void run(()=>activityAction('push-off',{}),'이 행성의 푸시 알림을 껐어요.')} disabled={busy}>푸시 끄기</button><button onClick={()=>void run(()=>browserDb().auth.signOut(),'로그아웃했어요.')}><LogOut size={16}/>로그아웃</button></div></div>
 <Tabs value={tab} onValueChange={setTab} className="aw-tabs"><TabsList className="aw-tablist">{[['info','내 정보'],['awards','내 훈장'],['territory','내 영토'],['visits','방문 기록'],['photos','사진첩'],['history','활동 내역']].map(([id,name])=><TabsTrigger value={id} key={id}>{name}{id==='awards'&&d.notifications.some(n=>!n.read_at)&&<span className="aw-new">새 소식</span>}</TabsTrigger>)}</TabsList>
 <TabsContent value="info"><div className="aw-overview"><section className="aw-player aw-panel"><div className="aw-character"><CharacterArt planet={planet} index={d.profile.character_id??g.character} label={`${w.name}의 ${g.rank.name} 캐릭터`}/><span>{d.profile.character_name||g.rank.name}</span></div><div className="aw-player-details"><span className="aw-eyebrow">{w.name}의 {g.rank.name}</span><h2>{d.profile.nickname}</h2><p>{w.story}</p><div className="aw-level-number"><strong>레벨 {g.level}</strong><span>{g.rank.name}</span></div><div className="aw-exp-caption"><b>{d.xp.toLocaleString()} EXP</b><small>다음 레벨까지 {g.next-d.xp} EXP</small></div><Progress className="aw-progress" value={g.progress} aria-label={`다음 레벨까지 ${g.progress}%`}/><p className="aw-help">EXP는 활동으로 쌓는 경험치, 레벨은 누적 EXP에 따른 성장 단계예요.</p><div className="aw-actions"><Button onClick={()=>{setNickname(d.profile.nickname);setCharacter(d.profile.character_id??g.character);setCharacterName(d.profile.character_name);setEditor(true)}}>캐릭터 꾸미기</Button><button onClick={()=>setTab('territory')}>내 영토 보기 <ChevronRight size={16}/></button></div></div></section><section className="aw-panel aw-stats"><Title title="나의 스탯">어떻게 탐험했는지를 보여주는 활동 기록이에요.</Title>{[['explore','탐험력','인증한 새로운 매장'],['record','기록력','공개 제보와 사진'],['discover','발견력','채택된 상태 제보'],['steady','꾸준함','기여 활동을 한 날']].map(([key,label,desc])=><div className="aw-stat" key={key}><div><b>{label}</b><strong>{d.stats[key as keyof typeof d.stats]}</strong></div><Progress value={Math.min(100,d.stats[key as keyof typeof d.stats]*5)} className="aw-progress" aria-label={label}/><small>{desc}</small></div>)}</section></div>
 <section className="aw-panel"><Title title="오늘의 퀘스트">한국 시간 자정에 새로 열려요. 조건을 완료하면 경험치가 자동으로 쌓여요.</Title><div className="aw-quests">{d.quests.map(q=><article key={q.id} className={q.done?'done':''}><span className="aw-quest-icon">{q.done?<Check/>:q.id==='visit'?<MapPin/>:q.id==='report'?<BookOpen/>:<Shield/>}</span><h3>{q.title}</h3><p>{q.id==='report'?'사진과 함께 한 접시를 제보해요.':q.id==='visit'?'매장에서 GPS와 결제를 인증해요.':'영업·품절 정보가 채택되면 완료돼요.'}</p><b>+{q.xp} EXP</b>{q.done?<span className="aw-pill is-earned">오늘 완료</span>:<button onClick={()=>q.id==='report'?location.assign('/suggestion#report'):(setForm(q.id==='visit'?'receipt':'status'),setStore(null))}>{q.id==='report'?'제보하기':q.id==='visit'?'방문 인증':'상태 제보'}</button>}</article>)}</div><p className="aw-help">활동 EXP: 제보 +30 · 방문 인증 +40 · 인증 방문의 첫 사진 +20 · 채택된 상태 제보 +15. 같은 종류의 보상은 하루 3회, 같은 기록은 1회 반영해요. 퀘스트 보상은 각 하루 1회 추가돼요.</p></section>
 <section className="aw-panel"><Title title="나의 레벨">한 접시씩 기록하며 탐험가에서 왕의 자리까지 올라가요.</Title><div className="aw-ranks">{RANKS.map((r,i)=><article key={r.name} className={g.level>=r.level?'unlocked':''}><CharacterArt planet={planet} index={i} label={`${w.name}의 ${r.name} 캐릭터`}/><small>레벨 {r.level}</small><h3>{r.name}</h3><p>{r.xp.toLocaleString()} EXP</p></article>)}</div></section>
 <section className="aw-panel"><Title title="나의 카드">캐릭터·레벨·EXP·스탯·훈장을 한 장에 담아 자랑해요.</Title><div className="aw-actions"><Button onClick={()=>setCardOpen(true)}><Share2 size={17}/>내 카드 이미지 공유</Button><button onClick={()=>void run(()=>activityAction('revoke-share',{}),'기존 공유 링크를 모두 닫았어요.')} disabled={busy}>공유 링크 닫기</button></div>{shareUrl&&<input readOnly aria-label="나의 카드 공유 링크" value={shareUrl} onFocus={e=>e.target.select()}/>}<p className="aw-help">공유 카드는 현재 전적을 담아요. 영수증·결제 내역·예약·정확한 위치는 공개하지 않아요.</p></section></TabsContent>
 <TabsContent value="awards"><section className="aw-panel"><Title title="나의 훈장">처음의 발걸음부터 꾸준한 취향까지, 나의 전적이 휘장이 돼요.</Title><div className="aw-badges">{BADGES.map(b=>{const owned=d.awards.find(a=>a.badge_id===b.id);return <article key={b.id} className={owned?'owned':''}><img src={asset(b.image+'.svg')} alt={`${b.name} 휘장`}/><h3>{b.name}</h3><p>{b.rule}</p>{owned?<><span className="aw-pill is-earned">{date(owned.earned_at)} 획득</span><button disabled={busy} onClick={()=>void run(()=>activityAction('profile',{equippedBadge:b.id}),'대표 훈장으로 달았어요.')}>{d.profile.equipped_badge===b.id?'대표 훈장':'대표로 달기'}</button></>:<span className="aw-pill">아직 잠겨 있어요</span>}</article>})}</div></section>
 <section className="aw-panel aw-limited"><span className="aw-limited-banner">LIMITED EDITION</span><strong className="aw-only">ONLY AT THAT MOMENT</strong><Title title="그때만의 휘장">이벤트·프로모션·콜라보 기간에만 획득하고, 내 전적에는 오래 간직해요.</Title>{d.awards.filter(a=>a.limited).length>0&&<div className="aw-badges">{d.awards.filter(a=>a.limited).map(a=><article className="owned" key={a.id}><img src={asset(a.image+'.svg')} alt={a.title}/><h3>{a.title}</h3><p>{date(a.earned_at)} 획득 · 소장 중</p><button onClick={()=>void run(()=>activityAction('profile',{equippedBadge:a.badge_id}),'한정판 휘장을 달았어요.')}>대표로 달기</button></article>)}</div>}{d.campaigns.length>0&&<div className="aw-quests">{d.campaigns.map(c=><article key={c.id}><h3>{c.title}</h3><p>{c.brand} · 참여 매장 {c.target_visits}회 인증</p><small>{date(c.starts_at)}–{date(c.ends_at)}</small></article>)}</div>}<div className="aw-brand-examples">{w.brands.map(([brand,title,image])=><article key={brand}><img src={asset(image+'.svg')} alt={`${brand} 협업 휘장 예시`} loading="lazy"/><span className="aw-example">협업 예시</span><h3>{title}</h3><p>{brand}</p></article>)}</div><p className="aw-help">위 브랜드 휘장은 협업 제안 예시예요. 실제 제휴·이벤트가 확정된 상품이나 획득한 휘장이 아닙니다.</p></section>
 <section className="aw-panel"><Title title="다정한 소식">새 훈장이 찾아온 순간을 모았어요.</Title><button onClick={()=>void run(()=>activityAction('read',{}),'새 소식을 모두 읽었어요.')}>모두 읽음</button>{!d.notifications.length?<Empty>첫 훈장이 찾아오면 이곳에서 알려드릴게요.</Empty>:d.notifications.map(n=><article className="aw-notice" key={n.id}><Bell size={20}/><div><h3>{n.title}</h3><p>{n.body}</p><small>{date(n.created_at)} · {n.read_at?'읽음':'새 소식'}</small></div></article>)}</section></TabsContent>
 <TabsContent value="territory"><section className="aw-panel"><Title title="나의 영토">인증한 한 접시가 내가 정복한 장소로 남아요. 지역에서 세계까지 펼쳐보세요.</Title><div className="aw-territory-counts"><span><b>{d.counts.places}</b> 정복한 매장</span><span><b>{new Set(visits.map(v=>v.country+v.region)).size}</b> 지역</span><span><b>{d.counts.countries}</b> 국가</span></div><div className="aw-scales" aria-label="영토 범위">{[['region','지역'],['country','국가'],['world','세계']].map(([id,label])=><button key={id} aria-pressed={scale===id} onClick={()=>setScale(id as typeof scale)}>{label}</button>)}</div>{scale!=='world'&&<div className="aw-location-filters"><label>국가<select value={country} onChange={e=>{setCountry(e.target.value);setRegion('')}}>{[...new Set(['KR',...visits.map(v=>v.country)])].map(x=><option key={x} value={x}>{countryName(x)}</option>)}</select></label>{scale==='region'&&<label>지역<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">모든 지역</option>{[...new Set(visits.filter(v=>v.country===country).map(v=>v.region))].map(x=><option key={x}>{x}</option>)}</select></label>}</div>}<div className="aw-territory-map"><img src={asset(`planet-${planet}.webp`)} alt="" aria-hidden="true"/><div className="aw-territory-grid">{[...groups].map(([name,logs])=><button key={name} onClick={()=>{if(scale==='world'){setCountry(name);setScale('country')}else if(scale==='country'){setRegion(name);setScale('region')}else setTab('visits')}}><Flag size={20}/><strong>{scale==='world'?countryName(name):name}</strong><span>{logs.length}회 인증 · {new Set(logs.map(v=>v.store_id)).size}곳</span></button>)}</div>{!groups.size&&<Empty>아직 정복한 영토가 없어요. 첫 방문이 작은 깃발이 됩니다.</Empty>}</div></section></TabsContent>
 <TabsContent value="visits"><section className="aw-panel"><Title title="다녀온 곳">{w.name}에서 남긴 방문과 감각만 모았어요.</Title><div className="aw-actions"><button onClick={()=>{setStore(null);setForm('receipt')}}>GPS·결제 인증하기</button></div>{d.visits.length?<VisitList visits={d.visits} onShare={v=>void run(async()=>{const text=`${w.name} · ${v.shop}\n${v.visited_on} · ${v.menu}\n${v.note}\n${v.status==='verified'?'GPS·결제 방문 인증':'나의 방문 기록'}`;if(navigator.share)await navigator.share({title:v.shop,text});else await navigator.clipboard.writeText(text)},'방문 기록을 공유했어요.')}/>:<Empty>첫 한 접시를 나의 기록으로 남겨보세요.</Empty>}</section></TabsContent>
 <TabsContent value="photos"><section className="aw-panel"><Title title="나의 사진첩">방문한 곳의 한 접시와 기억을 간직해요.</Title>{d.visits.length>0&&<form className="aw-photo-upload" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>api('/api/activity/photo',{method:'POST',body:f}),'사진첩에 한 장을 더했어요.')}}><label>방문 기록<select name="visitId" required>{d.visits.map(v=><option key={v.id} value={v.id}>{v.visited_on} · {v.shop}</option>)}</select></label><label>사진<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required/></label><Button disabled={busy}>사진 보관하기</Button></form>}<div className="aw-gallery">{d.photos.map(p=>{const v=d.visits.find(v=>v.id===p.visit_id);return <figure key={p.id}>{p.url?<img src={p.url} alt={`${v?.shop||'방문'} 사진`} loading="lazy"/>:<p>사진을 다시 불러와 주세요.</p>}<figcaption><b>{v?.shop}</b><span>{v?.visited_on}</span>{p.url&&<button onClick={()=>void run(async()=>{const response=await fetch(p.url!);if(!response.ok)throw new Error('사진 링크를 새로 불러와 주세요.');const blob=await response.blob();const file=new File([blob],'NOWGO_나의_한접시.webp',{type:'image/webp'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:v?.shop||'나의 한 접시'});else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}},'사진을 공유하거나 저장했어요.')}><Share2 size={14}/>사진 공유</button>}</figcaption></figure>})}</div>{!d.photos.length&&<Empty>아직 사진이 없어요. 방문 기록에 첫 사진을 보관해 주세요.</Empty>}</section></TabsContent>
 <TabsContent value="history"><section className="aw-panel"><Title title="모든 활동">지도 탐험·제보·인증·예약·웨이팅의 흐름을 확인해요.</Title>{d.events.length?<div className="aw-timeline">{d.events.map(e=><article key={e.id}><span className="aw-timeline-dot"/><div><strong>{e.title}</strong><p>{LABELS[e.status]||e.status}</p><small>{new Date(e.occurred_at).toLocaleString('ko-KR')}</small></div></article>)}</div>:<Empty>지도를 탐험하면 나의 첫 활동이 이곳에 남아요.</Empty>}</section>{d.reviews.length>0&&<section className="aw-panel"><Title title="매장 확인 요청">내 매장의 실제 결제·상태를 확인한 뒤 승인해 주세요.</Title>{d.reviews.map(r=><article className="aw-review" key={r.id}><h3>{r.shop}</h3><p>{r.kind==='receipt'?'영수증':'상태 제보'} · {r.label}</p>{r.path&&<a href={r.path} target="_blank" rel="noreferrer">영수증 사진 확인 ↗</a>}<div className="aw-actions"><Button disabled={busy} onClick={()=>void run(()=>activityAction('review',{kind:r.kind,id:r.id,accept:true}),'기록을 확인했어요.')}>확인·승인</Button><button disabled={busy} onClick={()=>void run(()=>activityAction('review',{kind:r.kind,id:r.id,accept:false}),'확인할 수 없는 기록으로 처리했어요.')}>반려</button></div></article>)}</section>}</TabsContent>
 </Tabs></>}
 {d&&<ShareCard data={d} open={cardOpen} onClose={()=>setCardOpen(false)} onLink={async()=>{const {path}=await activityAction<{path:string}>('share',{});const url=location.origin+path;setShareUrl(url);await navigator.clipboard.writeText(url);setMessage('프로필 링크를 복사했어요.')}}/>}
 {message&&<div className="aw-toast" role="status">{message}<button aria-label="알림 닫기" onClick={()=>setMessage('')}>×</button></div>}
 <Dialog open={editor} onOpenChange={setEditor}><DialogContent className="aw-edit-dialog activity-world" style={{'--planet':w.accent} as CSSProperties}><DialogTitle>나의 캐릭터</DialogTitle><DialogDescription>대표 메뉴를 든 2등신 캐릭터와 모험해요. AI로 제작한 여섯 외형 중 뽑아 이름을 붙일 수 있어요. 외형은 레벨과 별개예요.</DialogDescription><CharacterArt className="aw-edit-character" planet={planet} index={character} label={RANKS[character].name}/><button onClick={()=>setCharacter((character+1+Math.floor(Math.random()*5))%6)}><Sparkles size={17}/>캐릭터 뽑기</button><label>닉네임<Input value={nickname} maxLength={30} onChange={e=>setNickname(e.target.value)}/></label><label>캐릭터 이름<Input value={characterName} maxLength={30} onChange={e=>setCharacterName(e.target.value)}/></label><Button disabled={busy||!nickname.trim()} onClick={()=>void run(async()=>{await activityAction('profile',{nickname,characterId:character,characterName});setEditor(false)},'이제 나만의 캐릭터예요.')}>이 캐릭터와 모험하기</Button></DialogContent></Dialog>
 <Dialog open={!!form} onOpenChange={open=>!open&&setForm(null)}><DialogContent className="aw-form-dialog activity-world" style={{'--planet':w.accent} as CSSProperties}><DialogTitle>{form==='visit'?'다녀온 곳 등록':form==='receipt'?'방문 인증':'상태 제보'}</DialogTitle><DialogDescription>{form==='receipt'?'매장에서 GPS를 켜 주세요. 연동된 결제가 없다면 영수증을 보내 매장 확인을 받을 수 있어요.':form==='status'?'직접 확인한 매장의 지금을 알려주세요. 점주가 채택하면 EXP를 받아요.':'기억은 바로 저장돼요. GPS와 결제가 확인되면 방문 인증과 영토에 반영돼요.'}</DialogDescription><form onSubmit={submit}><StorePicker selected={store} onSelect={setStore} manual={false} onManual={()=>location.assign('/suggestion#report')}/>{form==='receipt'?<><button type="button" disabled={!store||busy} className="aw-button" onClick={()=>store&&void run(async()=>{const r=await captureVisit(store.id);setMessage(r.matched?'방문이 인증됐어요!':'GPS를 확인했어요. 30분 이내의 결제 기록과 연결할게요.')},'위치 확인을 마쳤어요. 결제가 확인되면 자동으로 반영돼요.')}><MapPin size={18}/>현재 매장 위치 확인</button><p className="aw-help">매장 반경 150m · 위치 정확도 100m 이내 · GPS와 결제 시각 차이 30분 이내. 위치 확인은 버튼을 누른 순간만 진행해요.</p><label>영수증 사진<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required/></label><label>영수증 승인·거래번호<Input name="receiptRef" maxLength={100} required/></label><label>결제 일시<Input name="paidAt" type="datetime-local" required/></label><Button disabled={busy||!store}>영수증 확인 요청</Button></>:form==='status'?<><label>지금 상태<select name="state"><option value="open">영업 중이에요</option><option value="closed">문을 닫았어요</option><option value="sold_out">품절이에요</option><option value="available">다시 판매해요</option></select></label><label>확인한 내용<textarea name="note" maxLength={500} required/></label><Button disabled={busy||!store}>상태 제보하기</Button></>:<><div className="aw-form-row"><label>다녀온 날짜<Input name="date" type="date" required max={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)}/></label><label>먹은 메뉴<Input name="menu" maxLength={100} required/></label></div><div className="aw-form-row">{[['taste','맛 만족'],['texture','식감 만족']].map(([name,label])=><label key={name}>{label}<select name={name} defaultValue="3">{[1,2,3,4,5].map(x=><option key={x} value={x}>{x} / 5</option>)}</select></label>)}</div><label>한 입의 기억<textarea name="note" maxLength={1000}/></label><Button disabled={busy||!store}>나의 기록으로 남기기</Button></>}</form></DialogContent></Dialog>
 </div>
}
