'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {api} from '@/lib/client';
import './sponsor-admin.css';

type Event={id:string;planet:'hot'|'sweet'|'chewy';sponsor:string;title:string;prize_type:string;prize_label:string;eligibility:string;win_rate:number;starts_at:string;ends_at:string;status:'draft'|'active'|'paused'};
type Prize={id:string;event_id:string;claimed_by:string|null};
type Draw={id:string;event_id:string;prize_id:string|null;local_day:string};
const names={hot:'HOT',sweet:'SWEET',chewy:'RICH'};
export default function SponsorAdmin(){
 const [events,setEvents]=useState<Event[]>([]),[prizes,setPrizes]=useState<Prize[]>([]),[draws,setDraws]=useState<Draw[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[codes,setCodes]=useState<Record<string,string>>({});
 async function refresh(){try{const data=await api<{events:Event[];prizes:Prize[];draws:Draw[]}>('/api/sponsor-admin');setEvents(data.events);setPrizes(data.prizes);setDraws(data.draws);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 async function send(body:Record<string,unknown>,success:string){setBusy(true);setNotice('');try{await api('/api/sponsor-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice(success);await refresh()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const event={planet:f.get('planet'),sponsor:f.get('sponsor'),title:f.get('title'),prize_type:f.get('prize_type'),prize_label:f.get('prize_label'),eligibility:f.get('eligibility'),win_rate:Math.round(Number(f.get('win_percent'))*100),starts_at:new Date(String(f.get('starts_at'))).toISOString(),ends_at:new Date(String(f.get('ends_at'))).toISOString()};void send({action:'create',event},'초안을 만들었어요. 혜택 코드를 등록한 뒤 활성화하세요.');e.currentTarget.reset()}
 return <main className="sa-page"><header><a href="/">NOWGO</a><span>운영자 전용</span><h1>오늘의 이벤트 관리</h1><p>광고주 혜택을 등록하고 재고와 당첨 기록을 확인합니다. 승인된 이벤트만 사이트에 표시됩니다.</p></header>
  {loading?<p role="status">관리자 권한을 확인하고 있어요.</p>:error?<div role="alert" className="sa-error">{error}<p>관리자 계정으로 통합 로그인한 뒤 다시 열어 주세요.</p></div>:<>
   <section className="sa-panel"><h2>새 이벤트</h2><form onSubmit={create} className="sa-form"><label>사이트<select name="planet"><option value="hot">HOT</option><option value="sweet">SWEET</option><option value="chewy">RICH</option></select></label><label>광고주<input name="sponsor" required maxLength={100} placeholder="광고주 이름"/></label><label>이벤트 제목<input name="title" required maxLength={150} placeholder="오늘의 혜택 뽑기"/></label><label>혜택 종류<select name="prize_type"><option value="discount">할인권</option><option value="ticket">입장권</option><option value="voucher">교환권</option></select></label><label>혜택 이름<input name="prize_label" required maxLength={150} placeholder="예: 아이스크림 할인권"/></label><label>참여 조건<select name="eligibility"><option value="verified_activity">방문 인증 또는 채택된 제보</option><option value="login">로그인</option></select></label><label>당첨 확률 (%)<input name="win_percent" type="number" min="0" max="100" step="0.01" defaultValue="100" required/></label><label>시작 시각<input name="starts_at" type="datetime-local" required/></label><label>종료 시각<input name="ends_at" type="datetime-local" required/></label><button disabled={busy}>초안 만들기</button></form><p>실제 제휴 확정 후 코드와 약관을 확인하고 활성화하세요. 코드는 이 화면에서 다시 표시하지 않습니다.</p></section>
   <section className="sa-panel"><h2>이벤트 목록</h2>{events.length===0?<p>등록된 이벤트가 없습니다.</p>:events.map(event=>{const inventory=prizes.filter(p=>p.event_id===event.id),attempts=draws.filter(d=>d.event_id===event.id);return <article key={event.id} className="sa-event"><div><strong>{names[event.planet]} · {event.sponsor}</strong><h3>{event.title}</h3><p>{event.prize_label} · {event.status==='active'?'진행 중':event.status==='paused'?'일시 중지':'초안'}</p><small>{new Date(event.starts_at).toLocaleString('ko-KR')} ~ {new Date(event.ends_at).toLocaleString('ko-KR')} · 당첨 확률 {event.win_rate/100}%</small></div><div className="sa-metrics"><span>전체 코드 <b>{inventory.length}</b></span><span>남은 코드 <b>{inventory.filter(p=>!p.claimed_by).length}</b></span><span>참여 <b>{attempts.length}</b></span><span>당첨 <b>{attempts.filter(d=>d.prize_id).length}</b></span></div>{event.status!=='active'&&<label className="sa-codes">혜택 코드 (한 줄에 하나씩)<textarea value={codes[event.id]||''} onChange={e=>setCodes({...codes,[event.id]:e.target.value})} placeholder="광고주가 제공한 고유 코드"/><button disabled={busy||!codes[event.id]?.trim()} onClick={()=>{const list=(codes[event.id]||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);void send({action:'codes',eventId:event.id,codes:list},`${list.length}개 코드를 등록했어요.`);setCodes({...codes,[event.id]:''})}}>코드 등록</button></label>}<div className="sa-actions">{event.status!=='active'?<button disabled={busy} onClick={()=>void send({action:'status',eventId:event.id,status:'active'},'이벤트를 활성화했어요.')}>이벤트 활성화</button>:<button disabled={busy} onClick={()=>void send({action:'status',eventId:event.id,status:'paused'},'이벤트를 일시 중지했어요.')}>일시 중지</button>}</div></article>})}</section>
  </>}{notice&&<p role="status" className="sa-notice">{notice}</p>}
 </main>;
}
