'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {browserDb,ensureUnifiedSession} from '@/lib/supabase-browser';
import {api} from '@/lib/client';
import {APP_PARENT_ORIGIN,isAppLoginChannel} from '@/lib/app-embed';
import {growth,planetForVariant,type ActivitySnapshot} from '@/lib/activity/model';
import type {SiteVariant} from '@/lib/site-config';
import AppNativeSession from './app-native-session';
export default function AppCharacter({variant}:{variant:SiteVariant}){
 const [snapshot,setSnapshot]=useState<ActivitySnapshot|null>(null),[status,setStatus]=useState<'loading'|'guest'|'ready'|'error'>('loading'),[message,setMessage]=useState('');
 const request=useRef(0),popup=useRef<Window|null>(null),channel=useRef('');
 const refresh=useCallback(async()=>{const run=++request.current;try{await ensureUnifiedSession().catch(()=>{});const {data}=await browserDb().auth.getSession();if(run!==request.current)return;if(!data.session||data.session.user.is_anonymous){setSnapshot(null);setStatus('guest');return}const result=await api<ActivitySnapshot>('/api/activity/snapshot');if(run!==request.current)return;if(result.planet!==planetForVariant(variant)||!Number.isFinite(result.xp)||!result.profile||!Array.isArray(result.awards))throw Error('성장 정보를 다시 확인해 주세요.');setSnapshot(result);setStatus('ready');setMessage('')}catch(error){if(run===request.current){setSnapshot(null);setStatus('error');setMessage(error instanceof Error?error.message:'나의 기록을 불러오지 못했어요.')}}},[variant]);
 useEffect(()=>{const db=browserDb();let active=true;void refresh();const changed=()=>{if(active&&!document.hidden)void refresh()};const {data}=db.auth.onAuthStateChange(()=>{request.current++;setSnapshot(null);setStatus('loading');setTimeout(changed,0)});const receive=async(event:MessageEvent)=>{if(event.origin===APP_PARENT_ORIGIN&&event.source===window.parent&&event.data?.type==='nowgo:character-refresh'){changed();return}if(event.origin!==location.origin||!popup.current||event.source!==popup.current||event.data?.type!=='nowgo:form-session'||!isAppLoginChannel(channel.current)||event.data.channel!==channel.current)return;const tokens=event.data.session;if(typeof tokens?.access_token!=='string'||typeof tokens?.refresh_token!=='string'||tokens.access_token.length>20000||tokens.refresh_token.length>20000)return;try{const {error}=await db.auth.setSession(tokens);if(error)throw error;if(!active)return;popup.current?.close();popup.current=null;channel.current='';await refresh()}catch{if(active)setMessage('계정 연결을 다시 시도해 주세요.')}};window.addEventListener('message',receive);window.addEventListener('focus',changed);window.addEventListener('nowgo-activity-change',changed);window.addEventListener('hot-customer-change',changed);document.addEventListener('visibilitychange',changed);const timer=setInterval(changed,30000);return()=>{active=false;request.current++;clearInterval(timer);data.subscription.unsubscribe();window.removeEventListener('message',receive);window.removeEventListener('focus',changed);window.removeEventListener('nowgo-activity-change',changed);window.removeEventListener('hot-customer-change',changed);document.removeEventListener('visibilitychange',changed)}},[refresh]);
 function connect(event:React.MouseEvent<HTMLAnchorElement>){const bridge=(window as unknown as {webkit?:{messageHandlers?:{nowgo?:{postMessage:(data:unknown)=>void}}}}).webkit?.messageHandlers?.nowgo;if(bridge){event.preventDefault();bridge.postMessage({type:'nowgo:sign-in',brand:variant});setMessage('통합 로그인 후 나의 성장 기록을 불러옵니다.')}}
 const g=snapshot?growth(snapshot.xp):null;const equipped=snapshot?.awards.find(b=>b.badge_id===snapshot.profile.equipped_badge);const col=g?[0,1,2,3,3,4][Math.min(5,g.character)]:0;const row=variant==='hot'?0:variant==='sweet'?1:2;
 return <main className="app-character" data-flavor={variant}><AppNativeSession/><header><p>{variant.toUpperCase()} · 나의 성장</p><h1>내 캐릭터</h1></header>{status==='loading'?<p role="status">나의 성장 기록을 불러오는 중이에요.</p>:status==='guest'?<section className="character-panel character-empty"><h2>나의 모험을 이어가세요</h2><p>내 계정을 연결하면 웹에서 쌓은 레벨·경험치·휘장·캐릭터가 나타나요.</p><a className="character-login" href="/app/report-login?role=customer&mode=character" target="_top" onClick={connect}>내 계정 연결하기</a>{message&&<p role="status">{message}</p>}</section>:status==='error'?<section className="character-panel"><p role="alert">{message}</p><button type="button" onClick={()=>void refresh()}>다시 불러오기</button></section>:snapshot&&g?<><section className="character-panel character-hero"><div className="character-art" role="img" aria-label={g.rank.name+' 캐릭터'} style={{backgroundPosition:`${col*25}% ${row*50}%`}}/><p>{snapshot.profile.nickname}</p><h2>{snapshot.profile.character_name||g.rank.name}</h2><strong>레벨 {g.level} · {g.rank.name}</strong><p className="character-exp">{snapshot.xp.toLocaleString()} EXP</p><progress max={g.next-g.min} value={snapshot.xp-g.min} aria-label="다음 레벨까지 경험치"/><small>다음 레벨까지 {(g.next-snapshot.xp).toLocaleString()} EXP</small>{equipped&&<div className="equipped-badge"><img src={'/activity/'+encodeURIComponent(equipped.image)+'.svg'} alt={equipped.title}/><span>대표 휘장 · {equipped.title}</span></div>}</section><section className="character-panel"><h2>나의 휘장 <span>{snapshot.awards.length}</span></h2>{snapshot.awards.length?<div className="character-awards">{snapshot.awards.map(b=><article key={b.id}><img src={'/activity/'+encodeURIComponent(b.image)+'.svg'} alt={b.title}/><strong>{b.title}</strong><small>{b.limited?'한정판 · ':''}{new Date(b.earned_at).toLocaleDateString('ko-KR')}</small></article>)}</div>:<p>아직 획득한 휘장이 없어요.</p>}</section><section className="character-panel character-counts"><div><strong>{snapshot.counts.reports}</strong><span>나의 제보</span></div><div><strong>{snapshot.counts.places}</strong><span>인증한 매장</span></div><div><strong>{snapshot.counts.visits}</strong><span>방문 기록</span></div></section><p className="character-sync">웹과 같은 계정의 기록 · 30초마다 갱신</p></>:null}</main>
}
