'use client';
import {useEffect,useRef,useState} from 'react';
import {Globe,MapPin,SquarePen,Heart,UserRound,X} from 'lucide-react';
import {browserDb} from '@/lib/supabase-browser';
import {api} from '@/lib/client';
import {type SiteVariant} from '@/lib/site-config';
import OAuthButtons from './oauth-buttons';
import AppNativeSession from './app-native-session';
type View='home'|'map'|'report'|'regular'|'character';
const menus=[{id:'home',title:'행성',Icon:Globe},{id:'map',title:'지도',Icon:MapPin},{id:'report',title:'제보',Icon:SquarePen},{id:'regular',title:'단골리스트',Icon:Heart},{id:'character',title:'내 캐릭터',Icon:UserRound}] as const;
const planets=[{brand:'hot',image:'hot',name:'HOT',taste:'매운 한 접시'},{brand:'rich',image:'chewy',name:'RICH',taste:'진하고 고소한 맛'},{brand:'sweet',image:'sweet',name:'SWEET',taste:'달콤한 디저트'}] as const;
export default function AppShell({variant}:{variant:SiteVariant}){
 const [brand,setBrand]=useState<SiteVariant>(variant);
 const [stage,setStage]=useState<'entry'|'app'>('entry'),[view,setView]=useState<View>('home'),[preview,setPreview]=useState(false),[message,setMessage]=useState(''),[place,setPlace]=useState<string|null>(null);
 const frame=useRef<HTMLIFrameElement|null>(null);
 const detail=useRef<HTMLIFrameElement|null>(null);
 useEffect(()=>{let active=true;const db=browserDb();const check=async()=>{try{if(new URLSearchParams(location.search).get('login')==='1')return;const {data}=await db.auth.getSession();if(!active)return;if(!data.session||data.session.user.is_anonymous)return;const profile=await api<{customer:unknown;consentRequired:boolean}>('/api/customer/me');if(!active)return;if(!profile.customer||profile.consentRequired)return;setPreview(false);setStage('app');const wanted=new URLSearchParams(location.search).get('view');setView(wanted==='map'?'map':'home')}catch{if(active)setMessage('계정 연결을 다시 확인해 주세요.')}};void check();const {data}=db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){setStage('entry');setPreview(false);setView('home')}});return()=>{active=false;data.subscription.unsubscribe()}},[]);
 useEffect(()=>{const accept=(data:Record<string,unknown>)=>{if(data.brand!==brand)return;if(data.type==='nowgo:open-report'){setPlace(null);setView('report')}if(data.type==='nowgo:menu-selected'){const menu=data.menu as {placeId?:unknown}|undefined;if(typeof menu?.placeId==='string'&&/^nowgo-[a-f0-9-]{36}$|^reported-[a-f0-9]{24}$/.test(menu.placeId))setPlace(menu.placeId)}if(data.type==='nowgo:sign-in'){setPlace(null);setStage('entry')}if(data.type==='nowgo:report-saved')setMessage('제보가 접수됐어요. 지도에 반영됩니다.')};const local=(event:Event)=>accept((event as CustomEvent).detail);const child=async(event:MessageEvent)=>{const source=event.source,origin='https://'+brand+'.nowgo.space';if(event.origin!==origin||!event.data||typeof event.data!=='object'||(source!==frame.current?.contentWindow&&source!==detail.current?.contentWindow))return;const d=event.data;if(d.type==='nowgo:request-location'&&view==='map'&&source===frame.current?.contentWindow&&typeof d.requestId==='string'&&/^[a-f0-9-]{36}$/.test(d.requestId)){const reply=(value:object)=>source?.postMessage({type:'nowgo:location-result',requestId:d.requestId,...value},event.origin);if(!navigator.geolocation){reply({code:2});return}navigator.geolocation.getCurrentPosition(p=>reply({coords:{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}}),e=>reply({code:e.code}),{timeout:10000,maximumAge:60000});return}accept(d)};window.addEventListener('nowgo:app-event',local);window.addEventListener('message',child);return()=>{window.removeEventListener('nowgo:app-event',local);window.removeEventListener('message',child)}},[brand,preview,view]);
 function login(){location.assign('/app?login=1')}
 function select(value:SiteVariant){setBrand(value);setView('map');setPlace(null)}
 return <div className="consumer-shell" data-flavor={brand}><AppNativeSession/>{stage==='entry'?<section className="shell-entry"><img src="/images/nowgo-logo-20261007.png" alt="NOWGO"/><span>SPACE</span><h1>지금 바로 출발하세요</h1><div className="shell-login"><h2>통합회원 가입 및 로그인</h2><OAuthButtons flavor={variant} returnTo="/app/report-login?role=customer&mode=app" accountType="user" includeApple/></div><button className="shell-browse" onClick={()=>{setPreview(true);setStage('app');setView('home')}}>로그인 없이 화면 둘러보기</button>{message&&<p role="status">{message}</p>}</section>:<><header className="shell-top"><button className="shell-logo" aria-label="나우고 행성 홈" onClick={()=>setView('home')}><img src="/images/nowgo-logo-20261007.png" alt="NOWGO"/></button><div className="shell-tabs">{planets.map(p=><button key={p.brand} className={p.brand===brand?'active':''} onClick={()=>select(p.brand)}>{p.name}</button>)}</div></header><main className="shell-content">{view==='home'?<section className="shell-home"><div><p>NOWGO SPACE</p><h1>오늘은 어떤 맛의 행성으로?</h1><span>가고 싶은 맛을 골라 주세요.</span></div><div className="shell-planets">{planets.map(p=><button key={p.brand} className={'shell-planet '+p.brand} onClick={()=>select(p.brand)}><img src={'/activity/planet-'+p.image+'.webp'} alt={p.name+' 시티팝 행성'}/><strong>{p.name}</strong><span>{p.taste}</span></button>)}</div><p>행성을 누르면 해당 카카오지도가 열려요.</p></section>:view==='map'||view==='report'||view==='character'?<iframe ref={frame} key={brand+view} className="shell-frame" src={'https://'+brand+'.nowgo.space/app/'+view} title={menus.find(m=>m.id===view)?.title}/>:preview?<section className="shell-empty"><h1>내 단골리스트</h1><p>통합 로그인 후 내 단골과 스탬프를 확인할 수 있어요.</p><button onClick={login}>통합회원 로그인</button></section>:<iframe className="shell-regular" src={'https://nowgo.space/regular/home?flavor='+brand} title="내 단골리스트"/>}</main><nav className="shell-nav" aria-label="앱 메뉴">{menus.map(({id,title,Icon})=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)} aria-current={view===id?'page':undefined}><Icon size={22}/><span>{title}</span></button>)}</nav>{message&&<button className="shell-message" onClick={()=>setMessage('')}>{message}</button>}{place&&<div className="shell-detail" role="dialog" aria-modal="true" aria-label="매장 상세"><button onClick={()=>setPlace(null)} aria-label="상세 닫기"><X/></button><iframe ref={detail} src={'https://'+brand+'.nowgo.space/app/place?place='+encodeURIComponent(place)} title="매장 상세"/></div>}</>}</div>
}
