'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {browserDb} from '@/lib/supabase-browser';
import {api} from '@/lib/client';
import {APP_PARENT_ORIGIN,isAppLoginChannel} from '@/lib/app-embed';
import type {SiteVariant} from '@/lib/site-config';
export default function AppEntry({variant}:{variant:SiteVariant}){
 const router=useRouter();
 const popup=useRef<Window|null>(null),channel=useRef('');
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const check=useCallback(async()=>{const {data}=await browserDb().auth.getSession();if(!data.session||data.session.user.is_anonymous)return;const profile=await api<{customer:unknown;consentRequired:boolean}>('/api/customer/me');if(!profile.customer||profile.consentRequired){if(window.parent===window)router.push('/account/join?type=user&returnTo='+encodeURIComponent('/app/entry'));return}const payload={type:'nowgo:entry-ready',brand:variant};window.parent.postMessage(payload,APP_PARENT_ORIGIN);const bridge=(window as unknown as {webkit?:{messageHandlers?:{nowgo?:{postMessage:(data:unknown)=>void}}}}).webkit?.messageHandlers?.nowgo;bridge?.postMessage(payload)},[variant,router]);
 useEffect(()=>{let active=true;const accept=async(session:{access_token:string;refresh_token:string})=>{if(!active)return;try{const {error}=await browserDb().auth.setSession(session);if(error)throw error;popup.current?.close();popup.current=null;channel.current='';setBusy(false);await check()}catch{if(active){setBusy(false);setError('계정 연결을 다시 확인해 주세요.')}}};const receive=(event:MessageEvent)=>{if(event.origin!==location.origin||event.source!==popup.current||!popup.current)return;const data=event.data;if(data?.type!=='nowgo:form-session'||!isAppLoginChannel(channel.current)||data.channel!==channel.current)return;if(typeof data.session?.access_token==='string'&&typeof data.session?.refresh_token==='string')void accept(data.session)};const native=(event:Event)=>{const bridge=(window as unknown as {webkit?:{messageHandlers?:{nowgo?:unknown}}}).webkit?.messageHandlers?.nowgo;if(!bridge)return;const session=(event as CustomEvent).detail;if(typeof session?.access_token==='string'&&typeof session?.refresh_token==='string')void accept(session)};window.addEventListener('message',receive);window.addEventListener('nowgo:native-session',native);void check().catch(()=>{});return()=>{active=false;window.removeEventListener('message',receive);window.removeEventListener('nowgo:native-session',native)}},[check]);
 function connect(provider:'google'|'kakao'|'apple'){channel.current=crypto.randomUUID();popup.current=window.open('/app/report-login?role=customer&provider='+provider+'&channel='+encodeURIComponent(channel.current),'nowgo-entry-login','popup,width=480,height=760');if(!popup.current){setError('로그인 창을 허용해 주세요.');return}setBusy(true);setError('')}
 return <main className="nowgo-app-entry"><h1>통합회원 가입 및 로그인</h1><button type="button" className="app-entry-google" onClick={()=>connect('google')}>{busy?'Google 로그인 다시 열기':'Google 로그인'}</button><button type="button" className="app-entry-kakao" onClick={()=>connect('kakao')}>{busy?'카카오 로그인 다시 열기':'카카오 로그인'}</button><button type="button" className="app-entry-apple" onClick={()=>connect('apple')}>{busy?'Apple 로그인 다시 열기':'Apple로 로그인'}</button>{error&&<p role="alert">{error}</p>}</main>;
}
