'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import styles from './customer-trust.module.css';
type Case={id:string;source_type:string;source_id?:string;reason:string;evidence:string;state:string;proposed_points:number;explanation_deadline:string|null;explanation:string|null;review_note:string|null;appeal_until:string|null;appeal_note:string|null;created_at:string};
type Entry={id:string;event:string;delta:number;score_after:number;created_at:string};
type Snapshot={score:number;restrictedUntil:string|null;todayRecovered:number;cases:Case[];ledger:Entry[]};
type RequestFn=(method:'GET'|'POST',body?:Record<string,unknown>)=>Promise<unknown>;
const labels:Record<string,string>={pending:'검토 대기 · 차감 없음',notified:'소명 접수 중 · 차감 없음',confirmed:'검토 완료 · 차감 확정',dismissed:'차감 없음 · 종결',reversed:'차감 취소 · 복원',false_report:'고의·반복 허위 제보',malicious_report:'사진 조작·악의적 제보',noshow:'예약 노쇼',deduction:'검토 후 차감',restoration:'검토 오류 복원',report_reward:'정확한 상태 제보 채택',visit_reward:'예약 방문 완료'};
const time=(s:string)=>new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
async function fetchTrust(method:'GET'|'POST',body?:Record<string,unknown>){const r=await fetch('/api/customer-trust',{method,credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'신뢰 기록을 확인하지 못했어요.');return d;}
export function CustomerTrust({request=fetchTrust,dark=false}:{request?:RequestFn;dark?:boolean}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Case|null>(null),[note,setNote]=useState(''),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{const d=await request('GET') as Snapshot;setData(d);setError('')},[request]);
 useEffect(()=>{let alive=true;const run=()=>{if(alive&&!document.hidden)void refresh().catch(e=>alive&&setError(e.message))};run();const timer=setInterval(run,30000);window.addEventListener('focus',run);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',run)}},[refresh]);
 async function submit(e:FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);setError('');try{await request('POST',{action:'respond',caseId:selected.id,note});await refresh();setSelected(null);setNote('');setNotice('내용을 접수했어요. 검토 결과는 신뢰 기록에 반영됩니다.')}catch(e){setError(e instanceof Error?e.message:'접수하지 못했어요.')}finally{setBusy(false)}}
 const score=data?.score??100;const tier=score>=80?'신뢰 탐험가':score>=60?'양호 탐험가':score>=40?'주의 단계':'이용 보호 단계';const restricted=Boolean(data?.restrictedUntil&&Date.parse(data.restrictedUntil)>Date.now()&&score<40);
 return <section className={`${styles.wrap} ${dark?styles.dark:''}`} aria-label="나의 신뢰"><div className={styles.hero}><img src="/activity/city-trust.webp" alt="약속을 지키는 손님과 따뜻한 도시의 가게"/><div><span>MY TRUST CITY</span><h2>정확한 제보와<br/>약속을 지키는 방문.</h2><p>모험 EXP와 별도로 관리하는 나의 신뢰예요.</p></div></div>
 {error&&<p role="alert" className={styles.error}>{error}<button onClick={()=>void refresh().catch(e=>setError(e.message))}>다시 확인</button></p>}{notice&&<p role="status">{notice}</p>}
 {!data?<p role="status">내 계정의 신뢰 기록을 불러오고 있어요.</p>:<><div className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>통합 고객 ID · 세 지도 공통</span><h3>나의 신뢰점수</h3><strong className={styles.score}>{score}<small> / 100</small></strong><p className={styles.tier}>{tier}</p><progress max={100} value={score} aria-label={`신뢰점수 ${score}점`}/><p>오늘 회복 +{data.todayRecovered} / 최대 +5점</p>{restricted?<p className={styles.error}>새 예약은 {time(data.restrictedUntil!)}까지 제한돼요.{score===0?' 새 제보도 잠시 제한돼요.':''}</p>:score<60?<p>새 예약은 동시에 1건까지 접수할 수 있어요.</p>:<p>제보와 예약을 정상 이용할 수 있어요.</p>}<p className={styles.help}>EXP·레벨·훈장·단골은 보존돼요. 기존 예약 확인·취소와 이의신청은 계속 이용할 수 있어요.</p></article><article className={styles.card}><h3>최근 점수 변화</h3>{!data.ledger.length?<p>아직 변동 내역이 없어요. 100점에서 시작해요.</p>:data.ledger.map(x=><div className={styles.row} key={x.id}><div><b>{labels[x.event]||x.event}</b><small>{time(x.created_at)} · 반영 후 {x.score_after}점</small></div><strong className={x.delta<0?styles.minus:styles.plus}>{x.delta>0?'+':''}{x.delta}</strong></div>)}</article></div>
 <article className={styles.card}><h3>검토·소명·이의신청</h3><p>검토 중인 사건은 차감하지 않아요. 점주의 신고만으로 차감이 확정되지 않습니다.</p>{!data.cases.length?<p className={styles.help}>진행 중인 신뢰 검토가 없어요.</p>:data.cases.map(c=>{const deadline=c.state==='notified'?c.explanation_deadline:c.state==='confirmed'?c.appeal_until:null;const canRespond=Boolean(deadline&&Date.parse(deadline)>Date.now());return <article className={styles.case} key={c.id}><div className={styles.row}><b>{labels[c.reason]}</b><span>{labels[c.state]}</span></div><p>예상 또는 확정 차감 {c.proposed_points}점 · {time(c.created_at)}</p><p><b>확인 근거:</b> {c.evidence}</p>{c.review_note&&<p><b>검토 의견:</b> {c.review_note}</p>}{c.explanation&&<p><b>내 소명:</b> {c.explanation}</p>}{c.appeal_note&&<p><b>내 이의신청:</b> {c.appeal_note}</p>}{deadline&&<p>접수 마감: {time(deadline)}</p>}{canRespond&&<button disabled={busy} onClick={()=>{setSelected(c);setNote(c.state==='confirmed'?c.appeal_note||'':c.explanation||'')}}>{c.state==='confirmed'?'이의신청':'내용 소명하기'}</button>}</article>})}</article></>}
 <article className={styles.card}><h3>모두의 시간을 지키는 기준</h3><div className={styles.rules}><div><b>정확한 제보</b><p>고의·반복 허위 확정 −5점. 조작·악의적 제보 확정 −10점. 단순 착오와 정보 불일치만으로 차감하지 않아요.</p></div><div><b>예약 약속</b><p>15분 도착 유예 후 검토. 노쇼 확정 −10점, 최근 30일 내 두 번째부터 −20점. 미리 취소해 주세요.</p></div><div><b>다시 쌓는 신뢰</b><p>확인된 예약 방문 +2점, 채택된 정확한 상태 제보 +3점. 하루 최대 +5점, 100점까지 회복해요.</p></div></div><p className={styles.help}>사유 안내 후 72시간 소명 기회를 드려요. 확정 뒤 7일 내 이의신청할 수 있어요. 같은 사건은 한 번만 반영하고, 차감 오류가 인정되면 점수를 복원해요.</p></article>
 {selected&&<section className={styles.card} role="region" aria-label="소명·이의신청 작성"><h3>{selected.state==='confirmed'?'이의신청':'검토 내용 소명'}</h3><form onSubmit={submit}><label>발생 시각과 확인할 내용을 적어 주세요<textarea required minLength={10} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><p className={styles.help}>10–1,000자. 주민등록번호·결제정보 등 민감한 정보는 적지 마세요.</p><div className={styles.actions}><button type="button" onClick={()=>setSelected(null)}>닫기</button><button disabled={busy} type="submit">검토 요청 접수</button></div></form></section>}
 </section>
}
