-- All fixtures and their audit events are rolled back.
begin;
select set_config('owner.test_user',gen_random_uuid()::text,true);
select set_config('owner.test_other',gen_random_uuid()::text,true);
select set_config('owner.test_store',gen_random_uuid()::text,true);
select set_config('owner.test_menu',gen_random_uuid()::text,true);
select set_config('owner.test_verification',gen_random_uuid()::text,true);
insert into auth.users(id) values(current_setting('owner.test_user')::uuid),(current_setting('owner.test_other')::uuid);
insert into public.owners(id,status) values(current_setting('owner.test_user')::uuid,'active'),(current_setting('owner.test_other')::uuid,'active');
insert into public.stores(id,owner_id,name,address,category,slug) values(current_setting('owner.test_store')::uuid,current_setting('owner.test_user')::uuid,'Rollback fixture','서울특별시 중구 세종대로 110','음식점','rollback-'||current_setting('owner.test_store'));
insert into public.ng_business_verifications(id,user_id,business_number_hash,status) values(current_setting('owner.test_verification')::uuid,current_setting('owner.test_user')::uuid,md5(current_setting('owner.test_store')),'verified');
insert into public.ng_store_claims(user_id,store_id,business_verification_id,status) values(current_setting('owner.test_user')::uuid,current_setting('owner.test_store')::uuid,current_setting('owner.test_verification')::uuid,'approved');
insert into public.store_menu_items(id,store_id,name,price_text,position,active) values(current_setting('owner.test_menu')::uuid,current_setting('owner.test_store')::uuid,'First menu','8000원',0,true);
insert into public.ng_owner_featured_menus(store_id,menu_item_id,planet,taste_level,photo_path,photo_mime) values(current_setting('owner.test_store')::uuid,current_setting('owner.test_menu')::uuid,'hot',3,'featured/fixture','image/webp');
select set_config('owner.test_signup_photo',current_setting('owner.test_user')||'/'||current_setting('owner.test_store')||'/hot/signup/'||gen_random_uuid()::text||'.webp',true);
select set_config('owner.test_paid_photo',current_setting('owner.test_user')||'/'||current_setting('owner.test_store')||'/hot/'||gen_random_uuid()::text||'.webp',true);
select set_config('request.jwt.claims',json_build_object('sub',current_setting('owner.test_user'),'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
do $$ declare s uuid:=current_setting('owner.test_store')::uuid;m uuid:=current_setting('owner.test_menu')::uuid;begin
 if public.ng_map_can_publish(s,'hot') then raise exception 'Unpaid access granted';end if;
 if (public.ng_map_owner_dashboard('hot',s)#>>'{access,enabled}')::boolean then raise exception 'Unpaid dashboard exposed';end if;
 begin perform public.ng_map_save_menu(s,'hot',null,'Unpaid menu',8000,3,'얼큰한','분식',null);raise exception 'Unpaid write accepted';exception when insufficient_privilege then null;end;
 begin insert into public.ng_map_menu_details(menu_item_id,planet,taste_level,flavor,category,price,photo_path) values(m,'hot',3,'얼큰한','분식',8000,'fake');raise exception 'Direct profile write accepted';exception when insufficient_privilege then null;end;
 begin insert into storage.objects(bucket_id,name) values('ng-map-menu-photos',current_setting('owner.test_paid_photo'));raise exception 'Unpaid dashboard upload accepted';exception when insufficient_privilege then null;end;
 perform public.ng_map_confirm_signup_location(s,37.5665,126.978);
 insert into storage.objects(bucket_id,name) values('ng-map-menu-photos',current_setting('owner.test_signup_photo'));
 perform public.ng_map_adopt_signup_menu(s,'hot',m,8000,3,'얼큰한','분식',current_setting('owner.test_signup_photo'));
 if public.ng_map_can_register_menu(s,'hot') then raise exception 'First-menu registration reusable';end if;
 begin perform public.ng_map_adopt_signup_menu(s,'hot',m,100,1,'칼칼한','기타',current_setting('owner.test_signup_photo'));raise exception 'Unpaid edit through signup accepted';exception when insufficient_privilege then null;end;
 perform public.ng_map_register_contact('010-1234-5678','hot',s);
 perform public.ng_map_register_contact('010-1234-5678','hot',s);
 if (select count(*) from public.ng_map_owner_dashboard_links where owner_id=auth.uid())<>1 then raise exception 'Dashboard URL issuance not idempotent';end if;
 if exists(select 1 from public.ng_map_owner_link_messages where owner_id=auth.uid()) then raise exception 'SMS was queued';end if;
 perform set_config('owner.test_dashboard_link',(select id::text from public.ng_map_owner_dashboard_links where owner_id=auth.uid() and planet='hot'),true);
 if public.ng_map_dashboard_access('hot',current_setting('owner.test_dashboard_link')::uuid,s)->>'managementUrl'<>('https://hot.nowgo.space/owner/dashboard/'||current_setting('owner.test_dashboard_link')) then raise exception 'Unique URL not displayed';end if;
 if public.ng_map_issue_dashboard_link(s,'sweet')=public.ng_map_issue_dashboard_link(s,'rich') then raise exception 'Map links shared';end if;
 begin perform public.ng_map_dashboard_access('sweet',current_setting('owner.test_dashboard_link')::uuid,s);raise exception 'Cross-map link accepted';exception when insufficient_privilege then null;end;
end $$;
reset role;
insert into public.ng_paddle_subscriptions(owner_id,product,price_id,status,paid_until,verified_at,consent_version) values(current_setting('owner.test_user')::uuid,'hot','pri_01m4d46kazt8e590qejkz7d9wa','active',now()+interval '1 month',now(),'2026-10-08-paddle-krw-v1');
set local role authenticated;
do $$ declare s uuid:=current_setting('owner.test_store')::uuid;m uuid;v text;begin
 if not public.ng_map_can_publish(s,'hot') then raise exception 'Paid owner rejected';end if;
 if public.ng_map_can_publish(s,'sweet') or public.ng_map_can_publish(s,'rich') then raise exception 'Subscription leaked to other map';end if;
 begin perform public.ng_map_save_menu(s,'hot',null,'No photo',8000,3,'얼큰한','분식',null);raise exception 'Missing photo accepted';exception when raise_exception then if sqlerrm<>'photo_required' then raise;end if;end;
 insert into storage.objects(bucket_id,name) values('ng-map-menu-photos',current_setting('owner.test_paid_photo'));
 m:=public.ng_map_save_menu(s,'hot',null,'Photo menu',9000,4,'칼칼한','국물·면',current_setting('owner.test_paid_photo'));
 perform public.ng_map_set_menu_soldout(s,'hot',m,true);
 if not exists(select 1 from public.ng_map_hot_menu_catalog where id=m and soldout and map_menu_photo) then raise exception 'Menu not published or soldout missing';end if;
 if exists(select 1 from public.ng_map_sweet_menu_catalog where id=m) or exists(select 1 from public.ng_map_rich_menu_catalog where id=m) then raise exception 'Menu leaked to other map';end if;
 perform public.ng_map_set_menu_soldout(s,'hot',m,false);
 if exists(select 1 from public.ng_map_hot_menu_catalog where id=m and soldout) then raise exception 'Soldout reset failed';end if;
 perform public.ng_map_set_menu_taste(s,'hot',m,2,'알싸한','기타');
 if not exists(select 1 from public.ng_map_hot_menu_catalog where id=m and heat=2 and flavor='알싸한' and category='기타') then raise exception 'Taste not reflected on map';end if;
 begin perform public.ng_map_set_menu_taste(s,'hot',m,6,'크리미한','케이크');raise exception 'Invalid taste accepted';exception when raise_exception then if sqlerrm<>'invalid_taste' then raise;end if;end;
 foreach v in array array['open','temporary_closed','closed_for_day','ingredients_soldout','permanently_closed','break_time'] loop
  perform public.ng_map_set_status(s,'hot',v);
  if public.ng_map_owner_dashboard('hot',s)#>>'{state,status,value}'<>v then raise exception 'Status not reflected';end if;
 end loop;
 if jsonb_array_length(public.ng_map_owner_dashboard('hot',s)#>'{state,menus}')<>2 then raise exception 'Dashboard missing first or additional menu';end if;
 begin delete from storage.objects where bucket_id='ng-map-menu-photos' and name=current_setting('owner.test_paid_photo');exception when insufficient_privilege then null;end;
 if not exists(select 1 from public.ng_map_hot_menu_catalog where id=m) then raise exception 'Published photo reference lost';end if;
end $$;
reset role;
do $$ begin if not exists(select 1 from storage.objects where bucket_id='ng-map-menu-photos' and name=current_setting('owner.test_paid_photo')) then raise exception 'Referenced photo deleted';end if;end $$;
do $$ declare s uuid:=current_setting('owner.test_store')::uuid;begin
 update public.ng_paddle_subscriptions set status='canceled' where owner_id=current_setting('owner.test_user')::uuid;
 if not public.ng_map_can_publish(s,'hot') then raise exception 'Paid canceled period rejected';end if;
 update public.ng_paddle_subscriptions set refunded=true where owner_id=current_setting('owner.test_user')::uuid;
 if public.ng_map_can_publish(s,'hot') then raise exception 'Refunded access accepted';end if;
 update public.ng_paddle_subscriptions set refunded=false,verified_at=now()-interval '25 hours' where owner_id=current_setting('owner.test_user')::uuid;
 if public.ng_map_can_publish(s,'hot') then raise exception 'Stale verification accepted';end if;
 update public.ng_paddle_subscriptions set verified_at=now(),paid_until=now()-interval '1 second' where owner_id=current_setting('owner.test_user')::uuid;
 if public.ng_map_can_publish(s,'hot') then raise exception 'Expired access accepted';end if;
 update public.ng_paddle_subscriptions set paid_until=now()+interval '1 month',price_id='pri_01m4d46km9peen4fp9v1xvret0' where owner_id=current_setting('owner.test_user')::uuid;
 if public.ng_map_can_publish(s,'hot') then raise exception 'Wrong-price access accepted';end if;
 update public.ng_paddle_subscriptions set price_id='pri_01m4d46kazt8e590qejkz7d9wa' where owner_id=current_setting('owner.test_user')::uuid;
end $$;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('owner.test_other'),'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
do $$ begin
 if exists(select 1 from public.ng_map_owner_dashboard_links) then raise exception 'Other owner read private dashboard links';end if;
 begin perform public.ng_map_dashboard_access('hot',current_setting('owner.test_dashboard_link')::uuid,null);raise exception 'Other owner used dashboard link';exception when insufficient_privilege then null;end;
 begin perform public.ng_map_issue_dashboard_link(current_setting('owner.test_store')::uuid,'hot');raise exception 'Other owner issued link';exception when insufficient_privilege then null;end;
 begin perform public.ng_map_owner_dashboard('hot',current_setting('owner.test_store')::uuid);raise exception 'Other dashboard exposed';exception when insufficient_privilege then null;end;
 begin perform public.ng_map_set_status(current_setting('owner.test_store')::uuid,'hot','open');raise exception 'Other owner changed status';exception when insufficient_privilege then null;end;
 begin perform public.ng_map_register_contact('01012345678','hot',current_setting('owner.test_store')::uuid);raise exception 'Other owner registered contact';exception when insufficient_privilege then null;end;
end $$;
reset role;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('owner.test_user'),'role','authenticated','is_anonymous',true)::text,true);
set local role authenticated;
do $$ begin
 if public.ng_map_can_publish(current_setting('owner.test_store')::uuid,'hot') then raise exception 'Anonymous session gained access';end if;
 begin perform public.ng_map_register_contact('01012345678','hot',current_setting('owner.test_store')::uuid);raise exception 'Anonymous contact write accepted';exception when insufficient_privilege then null;end;
end $$;
reset role;
set local role anon;
do $$ begin
 begin perform public.ng_map_owner_dashboard('hot',null);raise exception 'Guest dashboard exposed';exception when insufficient_privilege then null;end;
 begin perform * from public.ng_map_owner_dashboard_links;raise exception 'Guest dashboard links exposed';exception when insufficient_privilege then null;end;
 begin perform public.ng_map_dashboard_access('hot',current_setting('owner.test_dashboard_link')::uuid,null);raise exception 'Guest used dashboard link';exception when insufficient_privilege then null;end;
 begin perform * from public.ng_owner_contacts;raise exception 'Guest phone data exposed';exception when insufficient_privilege then null;end;
 if (select count(*) from public.ng_map_hot_menu_catalog where owner_store_id=current_setting('owner.test_store')::uuid)<>2 then raise exception 'Public menu read failed';end if;
end $$;
reset role;
update public.stores set trust_disabled_at=now() where id=current_setting('owner.test_store')::uuid;
set local role anon;
do $$ begin if exists(select 1 from public.ng_map_hot_menu_catalog where owner_store_id=current_setting('owner.test_store')::uuid) then raise exception 'Suspended owner still published';end if;end $$;
reset role;
rollback;
select 'map_owner_workspace_tests_passed' as result;
