'use client';
import {useCallback,useEffect,useRef,useState,type CSSProperties,type FormEvent} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import OAuthButtons from '@/components/oauth-buttons';
import KakaoMap from '@/components/kakao-map';
import {api,ApiError} from '@/lib/client';
import {browserDb} from '@/lib/supabase-browser';
import {siteConfig,type SiteVariant} from '@/lib/site-config';
import OwnerPlan from './owner-plan';
import MenuFields from './menu-fields';
import styles from './owner-pages.module.css';
type Point={address:string;lat:number;lng:number};
export default function OwnerSignup({variant}:{variant:SiteVariant}){
 const theme=siteConfig(variant),router=useRouter(),formRef=useRef<HTMLFormElement>(null),mounted=useRef(true),request=useRef(0),saving=useRef(false);
 const [loggedIn,setLoggedIn]=useState<boolean|null>(null),[stores,setStores]=useState<{id:string;name:string}[]>([]),[store,setStore]=useState(''),[resume,setResume]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[address,setAddress]=useState(''),[point,setPoint]=useState<Point|null>(null),[search,setSearch]=useState<{text:string;requestId:number}|null>(null),[locationNote,setLocationNote]=useState('');
 const load=useCallback(async()=>{const run=++request.current;try{const result=await api<{stores:{id:string;name:string}[]}>('/api/owner/manage');if(!mounted.current||run!==request.current)return;setStores(result.stores||[]);setLoggedIn(true);setError('')}catch(e){if(!mounted.current||run!==request.current)return;if(e instanceof ApiError&&e.status===401)setLoggedIn(false);else{setLoggedIn(true);setError(e instanceof Error?e.message:'계정 정보를 확인하지 못했어요.')}}},[]);
 useEffect(()=>{mounted.current=true;const initial=setTimeout(()=>void load(),0);const {data}=browserDb().auth.onAuthStateChange(()=>{setTimeout(()=>{if(mounted.current&&!saving.current)void load()},0)});return()=>{mounted.current=false;request.current++;clearTimeout(initial);data.subscription.unsubscribe()}},[load]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saving.current)return;setError('');if(!store&&!point){setError('주소 검색으로 지도에서 매장 위치를 확인해 주세요.');return}const form=new FormData(event.currentTarget);if(store)form.set('storeId',store);if(resume){form.set('storeId',resume);form.set('resume','yes')}if(point){form.set('lat',String(point.lat));form.set('lng',String(point.lng));form.set('address',point.address)}saving.current=true;setBusy(true);try{await api('/api/owner/signup',{method:'POST',body:form});router.push('/owner/subscribe')}catch(e){if(e instanceof ApiError&&e.details?.partial&&typeof e.details.storeId==='string')setResume(e.details.storeId);setError(e instanceof Error?e.message:'가입을 완료하지 못했어요. 입력한 내용은 유지됩니다.')}finally{saving.current=false;if(mounted.current)setBusy(false)}}
 function located(next:Point){setPoint(next);setAddress(next.address);setLocationNote('매장 위치를 확인했습니다. 지도에서 위치를 확인해 주세요.')}
 return <main className={styles.shell} style={{'--owner-accent':theme.accent} as CSSProperties}><header className={styles.hero}><p className={styles.eyebrow}>{theme.name} · FOR STORE OWNERS</p><h1>{theme.name} 지도 점주 가입</h1><p>메뉴 사진 한 장부터 시작하세요.<br/>매장을 확인한 뒤 월 8,000원 구독으로 오늘의 영업과 메뉴를 관리합니다.</p></header><div className={styles.layout}><div className={styles.card}>
 {loggedIn===null?<p role="status">계정을 확인하고 있습니다.</p>:!loggedIn?<><h2>점주 계정으로 시작하기</h2><p>가입 후 휴대폰 번호를 입력하면 매장관리 전용 주소를 받을 수 있습니다.</p><OAuthButtons flavor={variant} accountType="owner" returnTo="/owner/signup"/><p className={styles.hint}>세 지도와 나우고의 통합계정으로 로그인합니다.</p></>:<><h2>매장과 연락처 등록</h2><p>관리 전용 주소를 받을 휴대폰 번호를 입력해 주세요.</p><form ref={formRef} className={styles.form} onSubmit={submit}>
 <fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0,display:'grid',gap:20}}>
 {stores.length>0&&!resume&&<label>등록할 매장<select value={store} onChange={e=>{setStore(e.target.value);setError('')}}><option value="">새 매장 등록</option>{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>}
 <section><h3>휴대폰 번호</h3><label>대표자 휴대폰 번호<input type="tel" name="phone" required autoComplete="tel-national" inputMode="tel" maxLength={13} placeholder="010-1234-5678" pattern="01[0-9\- ]{8,11}"/></label><p className={styles.hint}>매장관리 전용 URL 전달에 사용하며 공개 지도에 표시하지 않습니다.</p></section>
 {!store&&<><section><h3>사업자 정보</h3><div className={styles.fields}><label>사업자등록번호<input name="businessNumber" required inputMode="numeric" maxLength={12} placeholder="123-45-67890"/></label><label>개업연월일<input type="date" name="openingDate" required max={new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'})}/></label></div><label>사업자등록증의 대표자명<input name="representative" required maxLength={100} autoComplete="name"/></label><p className={styles.hint}>사업자등록증에 적힌 정보로 매장 소유권을 확인합니다.</p></section>
 <section><h3>매장 정보</h3><div className={styles.fields}><label>매장 이름<input name="shop" required maxLength={100} placeholder="간판에 적힌 이름"/></label><label>매장 업종<input name="storeCategory" required maxLength={80} placeholder="음식점, 카페 등"/></label></div><div className={styles.address}><label>대한민국 매장 주소<input name="address" required value={address} onChange={e=>{setAddress(e.target.value);setPoint(null);setLocationNote('')}} maxLength={300} placeholder="도로명 또는 지번 주소"/></label><button type="button" disabled={!address.trim()} onClick={()=>{setPoint(null);setLocationNote('주소를 확인하고 있습니다.');setSearch({text:address.trim(),requestId:Date.now()})}}>주소 검색</button></div><div className={styles.map}><KakaoMap menus={[]} onSelect={()=>{}} variant={variant} addressSearch={search} onAddressFound={located} onPoint={located} onAddressError={()=>{setPoint(null);setLocationNote('주소를 찾지 못했습니다. 정확한 도로명·지번 주소를 확인해 주세요.')}}/></div><p className={styles.hint} role="status">{locationNote||'주소 검색 후 지도에서 실제 매장 위치를 확인해 주세요.'}</p></section>
 <section><h3>첫 메뉴 등록</h3><div className={styles.fields}><label>메뉴 이름<input name="menu" required maxLength={100} placeholder="메뉴판의 실제 이름"/></label><label>가격 (원)<input name="price" type="number" inputMode="numeric" required min={100} max={1000000} step={1}/></label></div><label>메뉴 사진 (필수)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required/></label><p className={styles.hint}>직접 찍은 JPG·PNG·WebP 사진을 5MB 이하로 첨부해 주세요.</p><div className={styles.fields}><MenuFields variant={variant}/></div></section></>}
 <label className={styles.consent}><input type="checkbox" name="consent" value="yes" required/><span>[필수] <Link href="/signup-terms" target="_blank">가입 약관과 개인정보 수집·이용</Link>에 동의합니다. 휴대폰 번호는 가입 확인과 관리 URL 전달에 사용됩니다.</span></label>
 <button className={styles.primary} type="submit">{busy?'매장 확인·등록 중':resume?'등록 이어서 완료하기':'등록하고 구독 페이지로'}</button>
 </fieldset></form></>}
 {error&&<div className={`${styles.message} ${styles.error}`} role="alert">{error}</div>}<div className={styles.links}><Link href="/owner/subscribe">이미 등록했다면 구독 확인</Link><Link href="/">메뉴 지도로 돌아가기</Link></div>
 </div><OwnerPlan variant={variant}/></div></main>;
}
