'use client';
import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import Link from 'next/link';
import OAuthButtons from '@/components/oauth-buttons';
import {api,ApiError} from '@/lib/client';
import {browserDb} from '@/lib/supabase-browser';
import {siteConfig,type SiteVariant} from '@/lib/site-config';
import {MAP_SUBSCRIPTION_TERMS_VERSION} from '@/lib/map-subscription';
import OwnerPlan from './owner-plan';
import styles from './owner-pages.module.css';
type Status={provider?:string;ready:boolean;status:string;pending:boolean;expiresAt:string|null;cancelAtPeriodEnd:boolean;nextPaymentAt:string|null;isTest:boolean;checkedAt:number};
const date=(value:string)=>new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});
export default function OwnerSubscription({variant}:{variant:SiteVariant}){
 const theme=siteConfig(variant),mounted=useRef(true),sequence=useRef(0),saving=useRef(false);
 const [status,setStatus]=useState<Status|null>(null),[login,setLogin]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[confirmCancel,setConfirmCancel]=useState(false);
 const load=useCallback(async()=>{const run=++sequence.current;try{const result=await api<Status>('/api/owner/subscription');if(mounted.current&&run===sequence.current){setStatus({...result,checkedAt:Date.now()});setLogin(false);setError('')}}catch(e){if(mounted.current&&run===sequence.current){setStatus(null);setLogin(e instanceof ApiError&&e.status===401);setError(e instanceof Error?e.message:'구독 상태를 확인하지 못했어요.')}}},[]);
 useEffect(()=>{mounted.current=true;const initial=setTimeout(()=>void load(),0);const refresh=()=>{if(!saving.current&&!document.hidden)void load()};const {data}=browserDb().auth.onAuthStateChange(()=>{sequence.current++;setStatus(null);setConsent(false);setTimeout(()=>{if(mounted.current&&!saving.current)void load()},0)});window.addEventListener('focus',refresh);return()=>{mounted.current=false;sequence.current++;clearTimeout(initial);data.subscription.unsubscribe();window.removeEventListener('focus',refresh)}},[load]);
 const active=!!status&&!status.isTest&&status.status==='active'&&!!status.expiresAt&&Date.parse(status.expiresAt)>status.checkedAt;
 const ready=status?.provider==='paddle'&&status.ready&&!status.isTest;
 async function act(action:'start'|'refresh'|'cancel'){
  if(saving.current||action==='start'&&(!ready||!consent))return;saving.current=true;setBusy(true);setError('');setNotice('');
  try{const result=await api<{checkoutUrl?:string}>('/api/owner/subscription',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(action==='start'?{consentAccepted:true,consentVersion:MAP_SUBSCRIPTION_TERMS_VERSION}:{})})});if(action==='start'){if(!result.checkoutUrl)throw Error('결제 화면을 확인하지 못했어요. 다시 시도해 주세요.');const url=new URL(result.checkoutUrl);if(url.origin!=='https://nowgo.space'||url.username||url.password||url.pathname!=='/billing/paddle-checkout'||!/^txn_[a-z0-9]{26}$/.test(url.searchParams.get('_ptxn')||''))throw Error('결제 화면 주소를 확인하지 못했어요.');window.location.assign(url.href)}else{await load();setConfirmCancel(false);setNotice(action==='cancel'?'다음 회차 자동갱신을 해지했습니다. 결제된 기간 종료일까지 이용할 수 있습니다.':'구독 상태를 다시 확인했습니다.')}}catch(e){setError(e instanceof Error?e.message:'결제 연결을 확인하지 못했어요.')}finally{saving.current=false;if(mounted.current)setBusy(false)}
 }
 return <main className={styles.shell} style={{'--owner-accent':theme.accent} as CSSProperties}><header className={styles.hero}><p className={styles.eyebrow}>{theme.name} · MONTHLY SUBSCRIPTION</p><h1>{theme.name} 지도 점주 구독</h1><p>월 8,000원, 부가세 포함.<br/>영업현황과 사진이 있는 메뉴를 직접 관리하세요.</p></header><div className={styles.layout}><section className={styles.card} aria-label="구독 신청"><h2>{active?'구독 이용 중':'구독 시작하기'}</h2>
 {login?<><p>점주 계정으로 로그인한 뒤 매장을 등록해 주세요.</p><OAuthButtons flavor={variant} accountType="owner" returnTo="/owner/subscribe"/><div className={styles.actions}><Link href="/owner/signup" className={styles.primary}>점주 가입·매장 등록</Link></div></>:!status?<><p role="status">{error?'구독 정보를 불러오지 못했어요.':'구독 상태를 확인하고 있습니다.'}</p>{error&&<button disabled={busy} onClick={()=>void load()}>다시 확인</button>}</>:active?<><div className={styles.status}><strong>{status.cancelAtPeriodEnd?'자동갱신 해지 완료':'이용 중인 지도 구독'}</strong><p>이용 종료일: {date(status.expiresAt!)}{status.nextPaymentAt&&!status.cancelAtPeriodEnd&&<><br/>다음 결제일: {date(status.nextPaymentAt)}</>}</p></div><p>매장관리는 대시보드에 표시된 본인 전용 고유 URL에서 이용할 수 있습니다.</p>{!status.cancelAtPeriodEnd&&<>{confirmCancel?<div className={styles.message}><p>다음 회차부터 자동결제를 중단할까요? 현재 이용 기간은 유지됩니다.</p><div className={styles.actions}><button disabled={busy} onClick={()=>void act('cancel')}>자동갱신 해지 확인</button><button disabled={busy} onClick={()=>setConfirmCancel(false)}>계속 이용하기</button></div></div>:<button disabled={busy} onClick={()=>setConfirmCancel(true)}>다음 회차 자동갱신 해지</button>}</>}<div className={styles.actions}><button disabled={busy} onClick={()=>void act('refresh')}>{busy?'확인 중':'구독 상태 다시 확인'}</button></div></>:<>
 {!ready&&<div className={styles.status} role="status"><strong>결제 서비스 준비 중</strong><p>Paddle 심사가 완료되면 구독 결제가 열립니다. 현재는 결제가 진행되지 않습니다.</p></div>}{status.isTest&&<p>테스트 결제는 실제 이용 권한을 부여하지 않습니다.</p>}<p>먼저 매장을 등록하고, 선택한 지도의 월 구독을 신청해 주세요.</p>
 <label className={styles.consent}><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/><span>{theme.name} 지도 구독 월 8,000원(부가세 포함)을 Paddle에서 원화로 결제하고 이후 매월 자동 결제하는 데 동의합니다. 첫 결제는 신청 시 진행되며 다음 결제일은 구독 정보에 표시됩니다.</span></label>
 <div className={styles.actions}><button className={`${styles.primary} ${styles.full}`} disabled={busy||!ready||!consent} onClick={()=>void act('start')}>{busy?'결제 연결 중':ready?'월 8,000원 구독하기':'결제 서비스 준비 중'}</button><Link href="/owner/signup" className={styles.secondary}>점주 가입·매장 등록</Link><button disabled={busy} onClick={()=>void act('refresh')}>결제 완료 후 다시 확인</button></div></>}
 {error&&!login&&<div className={`${styles.message} ${styles.error}`} role="alert">{error}</div>}{notice&&<p className={styles.message} role="status">{notice}</p>}
 <details className={styles.details}><summary>정기결제·해지·환불 안내</summary><p>언제든 다음 회차 자동갱신을 해지할 수 있으며 결제된 기간 종료일까지 이용할 수 있습니다. 청약철회·환불은 이용약관과 관계 법령에 따릅니다. 나우고 스페이스와 각 지도 구독은 별도입니다.</p><Link href="/terms" target="_blank">이용약관 보기</Link></details><div className={styles.links}><Link href="/">메뉴 지도로 돌아가기</Link><a href="https://nowgo.space/account/withdraw">회원탈퇴·전체 서비스 종료</a></div>
 </section><OwnerPlan variant={variant}/></div></main>;
}
