import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=ts.transpileModule(readFileSync('lib/app-geolocation.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const requestId='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa';
function setup(native=false){const handlers=new Map(),sent=[];const parent={postMessage:(...args)=>sent.push(args)};const window={parent,addEventListener:(name,fn)=>handlers.set(name,fn),removeEventListener:(name)=>handlers.delete(name)};if(native)window.webkit={messageHandlers:{nowgo:{postMessage:data=>sent.push([data])}}};const exports={};vm.runInNewContext(source,{exports,require:()=>({appParentOrigin:()=> 'https://nowgo-planet-iphone.workspace-948032.chatgpt.site',isAppLoginChannel:value=>value===requestId}),window,navigator:{},crypto:{randomUUID:()=>requestId},location:{hostname:'hot.nowgo.space'},setTimeout,clearTimeout,Date,Number});return {source:exports.appGeolocation(),handlers,sent,parent}}
for(const native of [false,true]){const env=setup(native);let success=null,failure=null;env.source.getCurrentPosition(position=>success=position,error=>failure=error,{timeout:1000});assert.equal(env.sent[0][0].type,'nowgo:request-location');assert.equal(env.sent[0][0].brand,'hot');const payload={type:'nowgo:location-result',requestId,coords:{latitude:37.5,longitude:126.7,accuracy:20}};if(native){env.handlers.get('nowgo:location-result')({detail:payload})}else{const receive=env.handlers.get('message');receive({origin:'https://evil.test',source:env.parent,data:payload});assert.equal(success,null);receive({origin:'https://nowgo-planet-iphone.workspace-948032.chatgpt.site',source:{},data:payload});assert.equal(success,null);receive({origin:'https://nowgo-planet-iphone.workspace-948032.chatgpt.site',source:env.parent,data:{...payload,requestId:'wrong'}});assert.equal(success,null);receive({origin:'https://nowgo-planet-iphone.workspace-948032.chatgpt.site',source:env.parent,data:payload})}assert.equal(success.coords.latitude,37.5);assert.equal(failure,null);assert.equal(env.handlers.size,0)}
const env=setup();let error;env.source.getCurrentPosition(()=>assert.fail('Denied GPS must not invent coordinates'),result=>error=result,{timeout:1000});env.handlers.get('message')({origin:'https://nowgo-planet-iphone.workspace-948032.chatgpt.site',source:env.parent,data:{type:'nowgo:location-result',requestId,code:1}});assert.equal(error.code,1);assert.equal(env.handlers.size,0);
console.log('GPS bridge: trusted origins, source window, request matching, native reply, denied permission and listener cleanup passed.');
