import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {nowgoUrl,returnPath} from '../lib/integration-policy.ts';
const source=ts.transpileModule(readFileSync(new URL('../lib/unified-auth.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function fixture(){
 const env={NOWGO_AUTH_AUTHORIZE_URL:'https://nowgo.space/test/authorize',NOWGO_AUTH_TOKEN_URL:'https://nowgo.space/test/token',NOWGO_AUTH_USERINFO_URL:'https://nowgo.space/test/userinfo',NOWGO_AUTH_CLIENT_ID:'test-client',NOWGO_AUTH_CLIENT_SECRET:'test-secret',NOWGO_AUTH_REDIRECT_URI:'https://hot.example.test/api/auth/callback',NOWGO_SESSION_ENCRYPTION_KEY:'test-only-encryption-key-at-least-32-characters'};
 const requests=new Map(),sessions=new Map();
 const database={prepare(sql){let args;const stmt={bind(...v){args=v;return stmt},async run(){if(sql.startsWith('INSERT INTO unified_auth_requests'))requests.set(args[0],{verifier:args[1],return_to:args[2],expires_at:args[3]});if(sql.startsWith('INSERT INTO unified_sessions'))sessions.set(args[0],{subject:args[1],access_token:args[2],expires_at:args[3]});if(sql.startsWith('DELETE FROM unified_sessions'))sessions.delete(args[0]);return {}},async first(){if(sql.startsWith('DELETE FROM unified_auth_requests WHERE state_hash')){const r=requests.get(args[0]);requests.delete(args[0]);return r?.expires_at>args[1]?r:null}if(sql.startsWith('SELECT subject,access_token')){const r=sessions.get(args[0]);return r?.expires_at>args[1]?r:null}throw Error('Unhandled SQL') }};return stmt},async batch(statements){return Promise.all(statements.map(s=>s.run()))}};
 const m={exports:{}};new Function('require','module','exports',source)((name)=>name==='cloudflare:workers'?{env}:name==='./server'?{db:()=>database,session:()=>({fresh:true,id:'anonymous'})}:{nowgoUrl,returnPath},m,m.exports);
 return {...m.exports,env,requests,sessions};
}
test('unconfigured central auth cannot accept independent or legacy account sessions',async()=>{const f=fixture();f.env.NOWGO_AUTH_TOKEN_URL='';assert.equal(f.browserAuthConfig().ready,false);assert.equal(await f.unifiedMember(new Request('https://hot.example.test',{headers:{cookie:'hot_auth='+crypto.randomUUID()+crypto.randomUUID()}})),null);const r=await f.beginLogin(new Request('https://hot.example.test/api/auth/start'));assert.match(r.headers.get('location'),/connection=pending/)});
test('wrong callback origin is rejected before issuing state',async()=>{const f=fixture();const r=await f.beginLogin(new Request('https://other.example.test/api/auth/start'));assert.equal(r.status,503);assert.equal(f.requests.size,0)});
test('PKCE start, one-time callback, sealed token, revocation and logout',async()=>{const f=fixture();const start=await f.beginLogin(new Request('https://hot.example.test/api/auth/start?returnTo=%2F%23report'));const u=new URL(start.headers.get('location'));assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.equal(u.searchParams.get('code_challenge').length,43);const state=u.searchParams.get('state');assert.ok(start.headers.get('set-cookie').includes('HttpOnly'));assert.ok(start.headers.get('set-cookie').includes('Secure'));
 const original=globalThis.fetch;let active=true;globalThis.fetch=async(url,options)=>{if(String(url).endsWith('/token')){assert.equal(options.body.get('code_verifier'),[...f.requests.values()][0]?.verifier||options.body.get('code_verifier'));assert.equal(options.redirect,'error');return Response.json({access_token:'test-central-bearer',token_type:'Bearer',expires_in:3600})}assert.equal(options.headers.Authorization,'Bearer test-central-bearer');return Response.json({sub:'canonical-42',nickname:'맛잘알',status:active?'active':'suspended',phone_masked:'010****0000',phone_verified:true,verified_contribution_points:30})};
 try{const req=new Request('https://hot.example.test/api/auth/callback?code=once&state='+state,{headers:{cookie:'nowgo_hot_state='+state}});const r=await f.finishLogin(req);assert.equal(r.headers.get('location'),'/#report');assert.equal(f.requests.size,0);const cookie=r.headers.getSetCookie().find(x=>x.startsWith('nowgo_hot_auth=')).split(';')[0];assert.equal(f.sessions.size,1);assert.ok(![...f.sessions.values()][0].access_token.includes('test-central-bearer'));const authenticated=new Request('https://hot.example.test/api/customer/me',{headers:{cookie}});assert.equal((await f.unifiedMember(authenticated)).id,'nowgo:canonical-42');assert.match((await f.finishLogin(req)).headers.get('location'),/failed/);active=false;assert.equal(await f.unifiedMember(authenticated),null);await f.logoutUnified(authenticated);assert.equal(f.sessions.size,0)}finally{globalThis.fetch=original}
});
test('callback missing cookie state cannot establish membership',async()=>{const f=fixture();const r=await f.finishLogin(new Request('https://hot.example.test/api/auth/callback?code=forged&state=forged'));assert.match(r.headers.get('location'),/failed/);assert.equal(f.sessions.size,0)});
