import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const saves=sqliteTable('menu_saves',{id:text('id').primaryKey(),session:text('session').notNull(),menuId:text('menu_id').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('save_session_menu').on(t.session,t.menuId)]);
export const observations=sqliteTable('taste_observation',{id:text('id').primaryKey(),session:text('session').notNull(),role:text('role').notNull(),placeId:text('place_id'),menuId:text('menu_id'),shop:text('shop').notNull(),menu:text('menu').notNull(),address:text('address').notNull(),price:integer('price').notNull(),heat:integer('heat').notNull(),flavor:text('flavor').notNull(),observedAt:text('observed_at').notNull(),note:text('note').notNull(),lat:text('lat'),lng:text('lng'),status:text('status').notNull(),category:text('category').notNull().default('기타'),publicationKey:text('publication_key'),createdAt:text('created_at').notNull()},t=>[index('observation_session').on(t.session),uniqueIndex('observation_publication_unique').on(t.publicationKey)]);
export const media=sqliteTable('menu_media',{id:text('id').primaryKey(),observationId:text('observation_id').notNull(),session:text('session').notNull(),objectKey:text('object_key').notNull(),mime:text('mime').notNull(),rights:integer('rights').notNull(),moderation:text('moderation').notNull(),createdAt:text('created_at').notNull()});
export const events=sqliteTable('taste_events',{id:text('id').primaryKey(),session:text('session').notNull(),event:text('event').notNull(),target:text('target').notNull(),day:text('day').notNull(),source:text('source').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('event_unique').on(t.session,t.event,t.target,t.day)]);

// Customer identity is independent from phone ownership and store membership.
export const customers=sqliteTable('customers',{id:text('id').primaryKey(),nickname:text('nickname').notNull(),phone:text('phone_e164').notNull(),phoneVerifiedAt:text('phone_verified_at'),status:text('status').notNull().default('active'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('customer_phone_unique').on(t.phone)]);
export const credentials=sqliteTable('customer_credentials',{customerId:text('customer_id').primaryKey().references(()=>customers.id),passwordHash:text('password_hash').notNull(),updatedAt:text('updated_at').notNull()});
export const customerSessions=sqliteTable('customer_sessions',{tokenHash:text('token_hash').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('customer_session_owner').on(t.customerId)]);
export const customerConsents=sqliteTable('customer_consents',{id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),channel:text('channel').notNull(),scope:text('scope').notNull().default('nowgo'),granted:integer('granted').notNull(),version:text('version').notNull(),createdAt:text('created_at').notNull()},t=>[index('consent_owner_channel_time').on(t.customerId,t.channel,t.createdAt)]);
export const reviews=sqliteTable('menu_reviews',{id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),menuId:text('menu_id').notNull(),body:text('body').notNull(),heat:integer('heat').notNull(),visitVerifiedAt:text('visit_verified_at'),status:text('status').notNull().default('pending'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('review_owner_menu').on(t.customerId,t.menuId)]);
export const contributions=sqliteTable('contribution_ledger',{id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),sourceKind:text('source_kind').notNull(),sourceId:text('source_id').notNull(),points:integer('points').notNull(),verifiedBy:text('verified_by').notNull(),verifiedAt:text('verified_at').notNull(),revokedAt:text('revoked_at')},t=>[uniqueIndex('contribution_source_unique').on(t.sourceKind,t.sourceId),index('contribution_owner').on(t.customerId)]);
export const customerStores=sqliteTable('customer_store_links',{id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),placeId:text('place_id').notNull(),status:text('status').notNull().default('following'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('customer_store_unique').on(t.customerId,t.placeId)]);
export const authLimits=sqliteTable('auth_rate_limits',{id:text('id').primaryKey(),count:integer('count').notNull(),expiresAt:text('expires_at').notNull()});

// HOT stores no new passwords or phone numbers. The NOWGO provider owns identity.
export const unifiedAuthRequests=sqliteTable('unified_auth_requests',{stateHash:text('state_hash').primaryKey(),verifier:text('verifier').notNull(),returnTo:text('return_to').notNull(),expiresAt:text('expires_at').notNull()},t=>[index('unified_auth_expiry').on(t.expiresAt)]);
export const unifiedSessions=sqliteTable('unified_sessions',{tokenHash:text('token_hash').primaryKey(),subject:text('subject').notNull(),accessToken:text('access_token').notNull(),expiresAt:text('expires_at').notNull()},t=>[index('unified_session_expiry').on(t.expiresAt)]);
