import {publicationDecision} from '@/lib/integration-policy';
import {db,bucket,session,reply,validOrigin,failure,config} from '@/lib/server';
import {MENUS,FLAVORS,MENU_CATEGORIES} from '@/lib/menus';
import {env} from 'cloudflare:workers';
import {communityMenus,allMenus} from '@/lib/menu-catalog';
import {identity,customer,sha} from '@/lib/customer';
type Ctx={params:Promise<{action:string}>};
export async function GET(req:Request,{params}:Ctx){const {action}=await params;try{if(action==='config'){const {kakaoKey,chatUrl}=config();return reply(req,{kakaoKey,chatUrl})}if(action==='menus')return reply(req,{menus:await communityMenus()});if(action!=='state')return reply(req,{},404);const s=await identity(req);const [a,b]=await Promise.all([db().prepare('SELECT menu_id FROM menu_saves WHERE session = ?').bind(s.id).all(),db().prepare('SELECT id,menu,status,created_at FROM taste_observation WHERE session = ? ORDER BY created_at DESC LIMIT 20').bind(s.id).all()]);return reply(req,{saved:a.results.map(x=>x.menu_id),reports:b.results},200,s.fresh?s.id:undefined)}catch(e){return failure(req,e)}}
export async function POST(req:Request,{params}:Ctx){if(!validOrigin(req))return reply(req,{error:'요청 출처를 확인해 주세요.'},403);const {action}=await params;let key='';try{const member=await customer(req);const s=member?{id:member.id,fresh:false}:session(req);
 if(action==='state'){const p=await req.json() as {menuId:string;saved:boolean};if(!(await allMenus()).some(x=>x.id===p.menuId)||typeof p.saved!=='boolean')return reply(req,{error:'메뉴를 다시 선택해 주세요.'},400);if(p.saved)await db().prepare('INSERT OR IGNORE INTO menu_saves (id,session,menu_id,created_at) VALUES (?,?,?,?)').bind(crypto.randomUUID(),s.id,p.menuId,new Date().toISOString()).run();else await db().prepare('DELETE FROM menu_saves WHERE session = ? AND menu_id = ?').bind(s.id,p.menuId).run();return reply(req,{saved:p.saved},200,s.fresh?s.id:undefined)}
 if(action==='events'){const {event,target,source}=await req.json() as {event:string;target:string;source:string};if(!['theme_menu_impression','menu_detail_open','place_status_open','route_click','owner_info_view'].includes(event)||typeof target!=='string'||target.length>80)return reply(req,{},400);const now=new Date().toISOString();await db().prepare('INSERT OR IGNORE INTO taste_events (id,session,event,target,day,source,created_at) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),s.id,event,target,now.slice(0,10),['community','threads','x'].includes(source)?source:'direct',now).run();return reply(req,{recorded:true},200,s.fresh?s.id:undefined)}
 if(action!=='reports')return reply(req,{},404);
 if(!member)return reply(req,{error:'로그인한 회원만 제보를 제출할 수 있어요. 상단 통합 로그인에서 가입해 주세요.'},401);
 if(Number(req.headers.get('content-length')||0)>3_000_000)return reply(req,{error:'사진은 2MB 이하로 올려주세요.'},413);
 const f=await req.formData(),get=(k:string)=>String(f.get(k)||'').trim(),id=get('requestId');if(!/^[a-f0-9-]{36}$/.test(id))return reply(req,{error:'제보 번호 오류'},400);
 const prior=await db().prepare('SELECT id,status FROM taste_observation WHERE id = ? AND session = ?').bind(id,s.id).first();if(prior)return reply(req,prior,200,s.fresh?s.id:undefined);
 const role=get('role'),shop=get('shop'),menu=get('menu'),address=get('address'),price=Number(get('price')),heat=Number(get('heat')),flavor=get('flavor'),observed=get('observedAt'),note=get('note'),category=get('category')||'기타';
 if(!['customer','owner'].includes(role)||shop.length<2||shop.length>100||menu.length<2||menu.length>100||!/^서울(?:특별시)?\s/.test(address)||address.length>200||!Number.isInteger(price)||price<100||price>1000000||!Number.isInteger(heat)||heat<1||heat>5||!FLAVORS.slice(1).includes(flavor)||note.length>1000||!/^\d{4}-\d{2}-\d{2}$/.test(observed)||!Number.isFinite(Date.parse(observed))||new Date(observed)>new Date()||new Date(observed).toISOString().slice(0,10)!==observed||get('rights')!=='yes'||get('accuracy')!=='yes'||!MENU_CATEGORIES.includes(category))return reply(req,{error:'서울 주소, 메뉴, 가격, 확인 날짜와 사진 사용 동의를 확인해 주세요.'},400);
 const photo=f.get('photo');if(!(photo instanceof File)||photo.size===0||photo.size>2_000_000)return reply(req,{error:'권한이 있는 JPG·PNG·WebP 사진을 2MB 이하로 첨부해 주세요.'},400);const bytes=new Uint8Array(await photo.arrayBuffer());const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255,png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71,webp=new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';if(!jpg&&!png&&!webp)return reply(req,{error:'지원되는 이미지 파일을 올려주세요.'},400);
 const rate=await db().prepare('SELECT COUNT(*) AS n FROM taste_observation WHERE session = ? AND created_at > ?').bind(s.id,new Date(Date.now()-3600000).toISOString()).first<{n:number}>();if((rate?.n||0)>=10)return reply(req,{error:'한 시간에 10건까지 제보할 수 있어요.'},429);
 const matched=MENUS.find(x=>x.id===get('menuId'));let lat=matched?.lat,lng=matched?.lng,canonicalAddress=address,publicationKey:string|null=null,placeId=matched?.placeId;
 if(!matched){const restKey=(env as unknown as Record<string,string>).KAKAO_MAP_REST_KEY;if(!restKey)return reply(req,{error:'주소 확인 연결을 준비하고 있어요. 입력 내용은 유지됩니다.'},503);let geo:Response;try{geo=await fetch('https://dapi.kakao.com/v2/local/search/address.json?query='+encodeURIComponent(address),{headers:{Authorization:'KakaoAK '+restKey},signal:AbortSignal.timeout(8000)})}catch{return reply(req,{error:'주소 확인 서비스에 연결하지 못했어요. 입력 내용은 유지됩니다. 잠시 후 다시 시도해 주세요.'},503)}if(!geo.ok)return reply(req,{error:'주소를 확인하지 못했어요. 잠시 후 다시 시도해 주세요.'},503);const g=await geo.json() as {documents:{x:string,y:string,address:{address_name:string,region_1depth_name:string},road_address?:{address_name:string}}[]};if(g.documents?.length!==1||g.documents[0].address?.region_1depth_name!=='서울')return reply(req,{error:'서울의 정확한 도로명 주소와 건물 번호를 입력해 주세요.'},400);const d=g.documents[0];lat=Number(d.y);lng=Number(d.x);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<37.3||lat>37.8||lng<126.7||lng>127.3)return reply(req,{error:'서울 주소의 위치를 확인해 주세요.'},400);canonicalAddress=d.road_address?.address_name||d.address.address_name;publicationKey=await sha(canonicalAddress+'|'+shop.replace(/\s/g,'')+'|'+menu.replace(/\s/g,''));placeId='reported-'+(await sha(canonicalAddress+'|'+shop.replace(/\s/g,''))).slice(0,24);const duplicate=await db().prepare('SELECT id FROM taste_observation WHERE publication_key=?').bind(publicationKey).first();if(duplicate)return reply(req,{error:'같은 주소·가게·메뉴가 이미 등록되어 있어요. 기존 메뉴를 확인해 주세요.'},409)}
 const status=matched?'accepted_unverified':publicationDecision(observed,note),mime=jpg?'image/jpeg':png?'image/png':'image/webp',now=new Date().toISOString();key=`reports/${s.id}/${id}`;await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});
 await db().batch([db().prepare('INSERT INTO taste_observation (id,session,role,place_id,menu_id,shop,menu,address,price,heat,flavor,observed_at,note,lat,lng,status,category,publication_key,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,s.id,role,placeId??null,matched?.id??id,shop,menu,canonicalAddress,price,heat,flavor,observed,note,String(lat),String(lng),status,category,publicationKey,now),db().prepare('INSERT INTO menu_media (id,observation_id,session,object_key,mime,rights,moderation,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,id,s.id,key,mime,1,status==='published_unverified'?'published':'pending',now)]);return reply(req,{id,status},201,s.fresh?s.id:undefined)
 }catch(e){if(key)await bucket().delete(key).catch(()=>{});return failure(req,e)}}
export async function DELETE(req:Request,{params}:Ctx){if(!validOrigin(req))return reply(req,{},403);if((await params).action!=='reports')return reply(req,{},404);const s=await identity(req);try{const {id}=await req.json() as {id:string};const row=await db().prepare('SELECT object_key FROM menu_media WHERE observation_id = ? AND session = ?').bind(id,s.id).first<{object_key:string}>();if(row)await bucket().delete(row.object_key);await db().batch([db().prepare('DELETE FROM menu_media WHERE observation_id = ? AND session = ?').bind(id,s.id),db().prepare('DELETE FROM taste_observation WHERE id = ? AND session = ?').bind(id,s.id)]);return reply(req,{deleted:true})}catch(e){return failure(req,e)}}
